# Generated by Django 5.2.1 on 2026-03-24 07:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevelImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_level_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_level_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevelImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='education_level.educationlevelimportbatch')),
            ],
            options={
                'db_table': 'education_level_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_code', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField(unique=True)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_level',
                'ordering': ['sequence_order', 'display_name'],
                'indexes': [models.Index(fields=['level_code'], name='education_l_level_c_ed3e27_idx'), models.Index(fields=['sequence_order'], name='education_l_sequenc_de889c_idx'), models.Index(fields=['is_active'], name='education_l_is_acti_528815_idx'), models.Index(fields=['is_archived'], name='education_l_is_arch_828752_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('level_code'), name='education_level_level_code_ci_uniq')],
            },
        ),
    ]
