# Generated by Django 6.0.3 on 2026-03-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_level', '0002_fix_legacy_is_archived_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='educationlevel',
            name='education_l_is_arch_828752_idx',
        ),
        migrations.AddIndex(
            model_name='educationlevel',
            index=models.Index(fields=['deleted'], name='education_l_deleted_0882e2_idx'),
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='is_archived',
        ),
    ]
