# Generated by Django 6.0.3 on 2026-07-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0005_alter_educationlevel_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationlevel",
            name="fallback_action",
        ),
        migrations.RemoveField(
            model_name="educationlevel",
            name="fallback_insight",
        ),
        migrations.RemoveField(
            model_name="educationlevel",
            name="next_step_1",
        ),
        migrations.RemoveField(
            model_name="educationlevel",
            name="next_step_2",
        ),
        migrations.RemoveField(
            model_name="educationlevel",
            name="next_step_3",
        ),
    ]
