# Generated by Django 6.0.3 on 2026-07-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0006_remove_dead_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationlevel",
            name="max_age",
        ),
        migrations.RemoveField(
            model_name="educationlevel",
            name="min_age",
        ),
    ]
