# Generated by Django 5.2.5 on 2026-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("permanent", "Permanent"),
                    ("temporary", "Temporary"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
