# Generated by Django 6.0.3 on 2026-06-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_created_at_alter_job_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSkill',
        ),
    ]
