# Generated by Django 5.2.5 on 2026-03-18 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PinCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode_number", models.CharField(max_length=20)),
                ("city_name", models.CharField(max_length=100, null=True)),
                ("state_name", models.CharField(max_length=100, null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "pin_code",
            },
        ),
    ]
