# Generated by Django 6.0.3 on 2026-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobGenerationPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AI Job Generation',
                'verbose_name_plural': 'AI Job Generation',
                'managed': False,
            },
        ),
    ]
