# Generated by Django 6.0.3 on 2026-07-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobgenerationpanel",
            options={
                "managed": False,
                "permissions": [
                    ("generate_job", "Can generate AI job posting details")
                ],
                "verbose_name": "AI Job Generation",
                "verbose_name_plural": "AI Job Generation",
            },
        ),
    ]
