# Generated by Django 6.0.3 on 2026-04-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_mapped_domains_and_signal_strength'),
        ('education_level', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='education_level',
            field=models.ForeignKey(blank=True, help_text='Optional education level filter for the question (e.g., 10th, 12th).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='education_level.educationlevel'),
        ),
    ]
