# Generated by Django 6.0.3 on 2026-04-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_question_education_level'),
        ('stream', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='Optional stream filter for the question (e.g., Science, Commerce).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='stream.stream'),
        ),
    ]
