# Generated by Django 6.0.3 on 2026-04-29 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_repair_question_stream_id_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_attempt',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userresponse',
            name='assessment_user_question_unique',
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.assessmentattempt'),
        ),
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'attempt'), name='assessment_user_question_attempt_unique'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user'], name='assessment__user_id_255d8b_idx'),
        ),
    ]
