# Generated by Django 5.2.5 on 2026-05-04 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_repair_question_stream_id_column"),
        ("domain", "0013_domain_category_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "career_direction",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                (
                    "parent_support",
                    models.CharField(
                        choices=[
                            ("very_supportive", "Very Supportive"),
                            ("somewhat_supportive", "SomeWhat Supportive"),
                            ("neutral", "Neutral"),
                            ("not_supportive", "Not Supportive"),
                            ("notsure", "Not Sure"),
                        ],
                        default="neutral",
                        max_length=150,
                    ),
                ),
                ("concerns", models.JSONField(blank=True, default=list, null=True)),
                (
                    "career_values",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("user_goals", models.JSONField(blank=True, default=list, null=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "student_assessment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'assessment_user_question_unique'
                ) THEN
                    ALTER TABLE assessment_user_response
                    DROP CONSTRAINT assessment_user_question_unique;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'assessment_user_question_unique'
                ) THEN
                    ALTER TABLE assessment_user_response
                    ADD CONSTRAINT assessment_user_question_unique
                    UNIQUE (user, question);
                END IF;
            END $$;
            """,
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="domain",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="assessments", to="domain.domain"
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment.studentassessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="userresponse",
            constraint=models.UniqueConstraint(
                fields=("assessment", "question"), name="assessment_question_unique"
            ),
        ),
    ]
