# Generated by Django 6.0.3 on 2026-04-29 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessmentattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userresponse',
            name='assessment_user_question_attempt_unique',
        ),
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='assessment_attempt_question_unique'),
        ),
    ]
