# Generated by Django 5.2.5 on 2026-05-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_studentassessment_and_more"),
    ]

    operations = []
