# Generated by Django 5.2.5 on 2026-05-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_remove_userresponse_assessment_user_question_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassessment",
            name="parent_support",
            field=models.CharField(
                choices=[
                    ("very_supportive", "Very Supportive"),
                    ("somewhat_supportive", "SomeWhat Supportive"),
                    ("neutral", "Neutral"),
                    ("not_supportive", "Not Supportive"),
                    ("notsure", "Not Sure"),
                ],
                max_length=150,
            ),
        ),
    ]
