# Generated by Django 5.2.5 on 2026-05-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_alter_studentassessment_parent_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentassessment",
            name="current_step",
        ),
    ]
