# Generated by Django 6.0.3 on 2026-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_remove_studentassessment_current_step'),
        ('domain', '0015_remove_domain_aptitude_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='domain',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='domain.domain'),
        ),
    ]
