# Generated by Django 6.0.3 on 2026-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_seed_assessment_interest_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentinterestcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
