# Generated by Django 6.0.3 on 2026-05-07 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0012_alter_studentassessment_domain"),
        ("domain", "0016_remove_domain_domain_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassessment",
            name="domain_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category domain selected by the student.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_assessments",
                to="domain.domain",
            ),
        ),
        migrations.RemoveField(
            model_name="studentassessment",
            name="domain",
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Child domain selected by the student.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="domain.domain",
            ),
        ),
    ]
