# Generated by Django 6.0.3 on 2026-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0013_studentassessment_domain_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("background", "Background"),
                    ("interest", "Interest"),
                    ("academic_strength", "Academic Strength"),
                    ("skill_confidence", "Skill Confidence"),
                    ("exposure", "Exposure"),
                    ("work_preference", "Work Preference"),
                    ("readiness", "Readiness"),
                    ("aptitude", "Aptitude"),
                    ("personality", "Personality"),
                    ("work_style", "Work Style"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sequence_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the same education level and signal type.",
            ),
        ),
    ]
