# Generated by Django 5.2.5 on 2026-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0016_studentassessment_current_screen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassessment",
            name="current_screen",
            field=models.CharField(
                choices=[
                    ("education_level", "Education Level"),
                    ("stream", "Stream / Path"),
                    ("domain_category", "Domain Category"),
                    ("domain", "Domain"),
                    ("career_direction", "Career Direction"),
                    ("parent_support", "Parent Support"),
                    ("concerns", "Concerns"),
                    ("interest", "Interest Questions"),
                    ("aptitude", "Aptitude Questions"),
                    ("personality", "Personality Questions"),
                    ("work_style", "Work Style Questions"),
                    ("career_values", "Career Values"),
                    ("user_goals", "User Goals"),
                    ("complete", "Complete"),
                ],
                default="education_level",
                max_length=32,
            ),
        ),
    ]
