# Generated by Django 5.2.5 on 2026-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_alter_studentassessment_current_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('interest', 'Interest'), ('aptitude', 'Aptitude'), ('personality', 'Personality'), ('work_style', 'Work Style')], max_length=20),
        ),
    ]
