# Generated by Django 6.0.3 on 2026-05-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_remove_unused_dimensions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="score_value",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="score_value",
        ),
    ]
