# Generated by Django 5.2.5 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0019_remove_option_score_value_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="studentassessment",
                    name="updated_at",
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
