# Generated by Django 5.2.5 on 2026-05-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0021_recommendation_models_and_remove_career_direction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Concern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentcareerrecommendation",
            options={"ordering": ["rank", "-score"]},
        ),
        migrations.AlterModelOptions(
            name="assessmentdomainscore",
            options={"ordering": ["assessment_id", "-score"]},
        ),
        migrations.AlterModelOptions(
            name="assessmentskillscore",
            options={"ordering": ["assessment_id", "-score"]},
        ),
        migrations.AlterModelOptions(
            name="optioncareermapping",
            options={"ordering": ["option_id", "career_id"]},
        ),
        migrations.AlterModelOptions(
            name="optionskillmapping",
            options={"ordering": ["option_id", "skill_id"]},
        ),
        migrations.RenameIndex(
            model_name="assessmentcareerrecommendation",
            new_name="assessment__assessm_3f7799_idx",
            old_name="acr_assessment_idx",
        ),
        migrations.RenameIndex(
            model_name="assessmentcareerrecommendation",
            new_name="assessment__career__6f2798_idx",
            old_name="acr_career_idx",
        ),
        migrations.RenameIndex(
            model_name="assessmentdomainscore",
            new_name="assessment__assessm_c256a9_idx",
            old_name="ads_assessment_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="assessmentskillscore",
            new_name="assessment__assessm_21e698_idx",
            old_name="ask_assessment_skill_idx",
        ),
        migrations.RemoveField(
            model_name="studentassessment",
            name="career_values",
        ),
        migrations.RemoveField(
            model_name="studentassessment",
            name="concerns",
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="current_screen",
            field=models.CharField(
                choices=[
                    ("education_level", "Education Level"),
                    ("stream", "Stream / Path"),
                    ("domain_category", "Domain Category"),
                    ("domain", "Domain"),
                    ("parent_support", "Parent Support"),
                    ("concerns", "Concerns"),
                    ("interest", "Interest Questions"),
                    ("aptitude", "Aptitude Questions"),
                    ("personality", "Personality Questions"),
                    ("work_style", "Work Style Questions"),
                    ("career_values", "Career Values"),
                    ("user_goals", "User Goals"),
                    ("complete", "Complete"),
                ],
                default="education_level",
                max_length=32,
            ),
        ),
        migrations.RemoveField(
            model_name="studentassessment",
            name="user_goals",
        ),
        migrations.AddField(
            model_name="careervalue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="careervalue",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="careervalue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="concern",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="concern",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="concern",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="career_values",
            field=models.ManyToManyField(blank=True, to="assessment.careervalue"),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="concerns",
            field=models.ManyToManyField(blank=True, to="assessment.concern"),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="user_goals",
            field=models.ManyToManyField(blank=True, to="assessment.usergoal"),
        ),
    ]
