# Generated by Django 6.0.3 on 2026-05-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0022_careervalue_concern_usergoal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassessment",
            name="career_values",
            field=models.ManyToManyField(
                blank=True, null=True, to="assessment.careervalue"
            ),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="concerns",
            field=models.ManyToManyField(
                blank=True, null=True, to="assessment.concern"
            ),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="current_screen",
            field=models.CharField(
                choices=[
                    ("education_level", "Education Level"),
                    ("stream", "Stream / Path"),
                    ("domain_category", "Domain Category"),
                    ("domain", "Domain"),
                    ("career_direction", "Career Direction"),
                    ("parent_support", "Parent Support"),
                    ("concerns", "Concerns"),
                    ("interest", "Interest Questions"),
                    ("aptitude", "Aptitude Questions"),
                    ("personality", "Personality Questions"),
                    ("work_style", "Work Style Questions"),
                    ("career_values", "Career Values"),
                    ("user_goals", "User Goals"),
                    ("complete", "Complete"),
                ],
                default="education_level",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="user_goals",
            field=models.ManyToManyField(
                blank=True, null=True, to="assessment.usergoal"
            ),
        ),
        migrations.CreateModel(
            name="CareerDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="career_direction",
            field=models.ManyToManyField(
                blank=True, null=True, to="assessment.careerdirection"
            ),
        ),
    ]
