# Generated by Django 6.0.3 on 2026-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0023_alter_studentassessment_career_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassessment",
            name="career_direction",
            field=models.ManyToManyField(blank=True, to="assessment.careerdirection"),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="career_values",
            field=models.ManyToManyField(blank=True, to="assessment.careervalue"),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="concerns",
            field=models.ManyToManyField(blank=True, to="assessment.concern"),
        ),
        migrations.AlterField(
            model_name="studentassessment",
            name="user_goals",
            field=models.ManyToManyField(blank=True, to="assessment.usergoal"),
        ),
    ]
