# Generated by Django 6.0.3 on 2026-05-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0024_alter_studentassessment_career_direction_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="careerdirection",
            table="assessment_career_direction",
        ),
        migrations.AlterModelTable(
            name="careervalue",
            table="assessment_career_value",
        ),
        migrations.AlterModelTable(
            name="concern",
            table="assessment_concern",
        ),
        migrations.AlterModelTable(
            name="usergoal",
            table="assessment_usergoal",
        ),
    ]
