# Generated by Django 6.0.3 on 2026-05-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_alter_careerdirection_table_alter_careervalue_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentcareerrecommendation',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='assessmentcareerrecommendation',
            name='assessment__assessm_3f7799_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentcareerrecommendation',
            name='assessment__career__6f2798_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentdomainscore',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='assessmentdomainscore',
            name='assessment__assessm_c256a9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentskillscore',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='assessmentskillscore',
            name='assessment__assessm_21e698_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coursecareermapping',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='coursecareermapping',
            name='course_care_career__e51669_idx',
        ),
        migrations.AlterUniqueTogether(
            name='optionskillmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='optionskillmapping',
            name='option',
        ),
        migrations.RemoveField(
            model_name='optionskillmapping',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='assessmentcareerrecommendation',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentcareerrecommendation',
            name='career',
        ),
        migrations.RemoveField(
            model_name='assessmentdomainscore',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentdomainscore',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='assessmentskillscore',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentskillscore',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='coursecareermapping',
            name='career',
        ),
        migrations.RemoveField(
            model_name='coursecareermapping',
            name='course',
        ),
        migrations.DeleteModel(
            name='OptionCareerMapping',
        ),
        migrations.DeleteModel(
            name='OptionSkillMapping',
        ),
        migrations.DeleteModel(
            name='AssessmentCareerRecommendation',
        ),
        migrations.DeleteModel(
            name='AssessmentDomainScore',
        ),
        migrations.DeleteModel(
            name='AssessmentSkillScore',
        ),
        migrations.DeleteModel(
            name='CourseCareerMapping',
        ),
    ]
