# Generated by Django 6.0.3 on 2026-05-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_remove_static_recommendation_models'),
        ('career', '0003_alter_career_updated_at'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCareerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='career.career')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_mappings', to='courses.course')),
            ],
            options={
                'db_table': 'course_career_mapping',
                'ordering': ['career_id', '-relevance_score'],
                'indexes': [models.Index(fields=['career', 'course'], name='course_care_career__e51669_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'career'), name='course_career_mapping_course_career_uniq')],
            },
        ),
    ]
