# Generated by Django 6.0.3 on 2026-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0030_parentassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentassessment',
            name='profile_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
