# Generated by Django 6.0.3 on 2026-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_parentassessment_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentassessment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
