# Generated by Django 6.0.3 on 2026-06-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_strip_parentassessment_child_fields'),
        ('domain', '0020_remove_retired_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentassessment',
            name='career_direction',
            field=models.ManyToManyField(blank=True, to='assessment.careerdirection'),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='career_familiarity',
            field=models.CharField(blank=True, choices=[('very_aware', 'Very Aware'), ('somewhat_aware', 'Somewhat Aware'), ('limited_knowledge', 'Limited Knowledge'), ('not_aware', 'Not Aware')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='career_values',
            field=models.ManyToManyField(blank=True, to='assessment.careervalue'),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='concerns',
            field=models.ManyToManyField(blank=True, to='assessment.concern'),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='decision_style',
            field=models.CharField(blank=True, choices=[('stability_based', 'Stability Based'), ('interest_based', 'Interest Based'), ('income_based', 'Income Based'), ('family_advice_based', 'Family Advice Based')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='domain_category',
            field=models.ForeignKey(blank=True, help_text='Parent category domain selected by the parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category_assessments', to='domain.domain'),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='parent_support',
            field=models.CharField(blank=True, choices=[('very_supportive', 'Very Supportive'), ('somewhat_supportive', 'SomeWhat Supportive'), ('neutral', 'Neutral'), ('not_supportive', 'Not Supportive'), ('notsure', 'Not Sure')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='platform_expectations',
            field=models.ManyToManyField(blank=True, to='assessment.usergoal'),
        ),
        migrations.AlterField(
            model_name='parentassessment',
            name='current_screen',
            field=models.CharField(choices=[('domain_category', 'Domain Category'), ('career_direction', 'Career Direction'), ('parent_support', 'Parent Support'), ('concerns', 'Concerns'), ('parent_career_expectations', 'Parent Career Expectations'), ('limitations', 'Limitations'), ('career_familiarity', 'Career Familiarity'), ('decision_style', 'Decision Style'), ('career_values', 'Career Values'), ('platform_expectations', 'Platform Expectations'), ('complete', 'Complete')], default='domain_category', max_length=50),
        ),
        migrations.CreateModel(
            name='ParentCareerExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_parent_career_expectation',
            },
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='parent_career_expectations',
            field=models.ManyToManyField(blank=True, to='assessment.parentcareerexpectation'),
        ),
        migrations.CreateModel(
            name='ParentConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_parent_constraint',
            },
        ),
        migrations.AddField(
            model_name='parentassessment',
            name='limitations',
            field=models.ManyToManyField(blank=True, to='assessment.parentconstraint'),
        ),
    ]
