# Generated by Django 6.0.3 on 2026-06-30 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0038_parentassessment_domain"),
        ("domain", "0020_remove_retired_content_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessment_guidance_reason",
            },
        ),
        migrations.CreateModel(
            name="WorkConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessment_work_constraint",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "career_intention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("career_change", "Career Change"),
                            ("promotion_growth", "Promotion / Growth"),
                            ("upskill_learn_new_skills", "Upskill / Learn New Skills"),
                            ("start_own_business", "Start Own Business"),
                            ("find_a_job", "Find a Job"),
                            ("not_sure_yet", "Not Sure Yet"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_environment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remote_work_from_home", "Remote / Work from Home"),
                            ("hybrid_office_and_remote", "Hybrid (Office & Remote)"),
                            ("office_based", "Office Based"),
                            ("field_work_travel", "Field Work / Travel"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed_9_6_schedule", "Fixed 9-6 Schedule"),
                            ("flexible_hours", "Flexible Hours"),
                            ("project_based", "Project Based"),
                            ("freelance_contract", "Freelance / Contract"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "current_screen",
                    models.CharField(
                        choices=[
                            ("career_intention", "Career Intention"),
                            ("guidance_reason", "Guidance Reason"),
                            ("work_constraint", "Work Constraint"),
                            ("work_style", "Work Style"),
                            ("domain_category", "Domain Category"),
                            ("domain", "Domain"),
                            ("complete", "Complete"),
                        ],
                        default="career_intention",
                        max_length=32,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Child domain selected by the professional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_assessments",
                        to="domain.domain",
                    ),
                ),
                (
                    "domain_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent domain category selected by the professional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_category_assessments",
                        to="domain.domain",
                    ),
                ),
                (
                    "guidance_reasons",
                    models.ManyToManyField(blank=True, to="assessment.guidancereason"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_constraints",
                    models.ManyToManyField(blank=True, to="assessment.workconstraint"),
                ),
            ],
            options={
                "db_table": "professional_assessment",
                "ordering": ["-created_at"],
            },
        ),
    ]
