# Generated by Django 6.0.3 on 2026-07-02 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0040_professionalassessment_career_values_and_more"),
        ("domain", "0020_remove_retired_content_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="professionalassessment",
            index=models.Index(fields=["user"], name="professiona_user_id_09e9be_idx"),
        ),
        migrations.AddIndex(
            model_name="professionalassessment",
            index=models.Index(
                fields=["current_screen"], name="professiona_current_8bd719_idx"
            ),
        ),
    ]
