# Generated by Django 6.0.3 on 2026-06-30 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.CharField(blank=True, max_length=512)),
                ("content", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="news/images/"),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="news_news_publish_ad4867_idx"
                    ),
                    models.Index(
                        fields=["category"], name="news_news_categor_05ff13_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="news_news_is_publ_075179_idx"
                    ),
                ],
            },
        ),
    ]
