# Generated by Django 6.0.3 on 2026-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
