# Generated by Django 6.0.3 on 2026-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="news/images/"
            ),
        ),
    ]
