# Generated by Django 6.0.3 on 2026-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_courses_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("diploma", "Diploma"),
                    ("degree", "Degree"),
                    ("certification", "Certification"),
                    ("training", "Training"),
                ],
                max_length=20,
            ),
        ),
    ]
