# Generated by Django 6.0.3 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_courseinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("higher_secondary", "Higher Secondary"),
                    ("diploma", "Diploma"),
                    ("degree", "Degree"),
                    ("certification", "Certification"),
                    ("training", "Training"),
                ],
                max_length=20,
            ),
        ),
    ]
