# Generated by Django 6.0.3 on 2026-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_courses_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinquiry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("responded", "Responded"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
