# Generated by Django 6.0.3 on 2026-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseinquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
