# Generated by Django 6.0.3 on 2026-07-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_courses_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_overview',
            new_name='course_description',
        ),
    ]
