# Generated by Django 6.0.3 on 2026-07-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0003_alter_country_updated_at"),
        ("course", "0009_add_course_overview_field"),
        ("state", "0003_alter_state_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="country.country",
            ),
        ),
        migrations.AddField(
            model_name="courses",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="state.state",
            ),
        ),
    ]
