# Generated by Django 6.0.3 on 2026-07-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_add_country_state_to_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
