# Generated by Django 6.0.3 on 2026-07-10 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_update_course_provider_related_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the institute or school/college posting this course.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
