# Generated by Django 6.0.3 on 2026-07-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0016_add_professional_assessment_fk"),
        ("course", "0016_alter_courses_course_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinquiry",
            name="career_suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_inquiries",
                to="assessment_career.careersuggestion",
            ),
        ),
    ]
