# Generated by Django 6.0.3 on 2026-07-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_remove_courses_education_tags_courses_education_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="provider",
        ),
    ]
