# Generated by Django 5.2.5 on 2026-03-18 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=100)),
                ("amount", models.FloatField(default=0)),
                ("currency", models.CharField(max_length=5)),
                ("description", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(max_length=10, verbose_name="status of payment"),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        verbose_name="if charge succeeded or authorized for later capture",
                    ),
                ),
                ("captured", models.BooleanField(default=False)),
                ("payment_method", models.CharField(max_length=20)),
                ("invoice_no", models.IntegerField(default=0)),
                ("fiscal_year", models.CharField(max_length=10, null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "stripe_charge",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Subcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=100)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("enterpirse", "Enterpirse"),
                            ("peruser", "Peruser"),
                            ("on_premise", "On-Premise"),
                        ],
                        default="enterpirse",
                        max_length=50,
                    ),
                ),
                ("per_user_price", models.FloatField(default=0)),
                ("discount", models.FloatField(default=0)),
                ("sell_price", models.FloatField(default=0)),
                ("duration", models.CharField(max_length=150, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("in_active", "in_active")],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "subcription",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=150)),
                ("feature_status", models.BooleanField(default=False)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "subscription_feature",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, null=True)),
                ("invoice_date", models.DateField(null=True)),
                ("due_date", models.DateField(null=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("Performa Invoice", "Performa Invoice"),
                            ("Commercial Invoice", "Commercial Invoice"),
                        ],
                        default="Performa Invoice",
                        max_length=50,
                    ),
                ),
                ("quantity", models.FloatField(default=1)),
                ("sell_price", models.FloatField(default=0)),
                ("rate", models.FloatField(default=0)),
                ("gst_rate", models.FloatField(default=18)),
                ("amount", models.FloatField(default=0)),
                ("note", models.TextField(null=True)),
                ("sgst", models.FloatField(default=0)),
                ("cgst", models.FloatField(default=0)),
                ("total", models.FloatField(default=0)),
                ("payment_reference_id", models.CharField(max_length=150, null=True)),
                ("check_out_url", models.CharField(max_length=750, null=True)),
                ("active", models.BooleanField(default=False, null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "subscription_invoice",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sell_price", models.FloatField(default=0)),
                ("amount", models.FloatField(default=0.0)),
                ("duration", models.CharField(max_length=50)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                ("check_out_url", models.URLField(blank=True, null=True)),
                ("invoice_no", models.CharField(default="0", max_length=50)),
                (
                    "active",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Inactive",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "razor_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "payment_subscription",
            },
        ),
        migrations.CreateModel(
            name="PurchasedSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(max_length=50)),
                ("per_user_price", models.FloatField(default=0)),
                ("discount", models.FloatField(default=0)),
                ("sell_price", models.FloatField(default=0)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Cash", "Cash"),
                        ],
                        default="Cheque",
                        max_length=100,
                    ),
                ),
                ("payment_reference_id", models.CharField(max_length=150, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "purchased_subscription",
                "ordering": ["-id"],
            },
        ),
    ]
