# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('subscription_type', models.CharField(choices=[('subscription', 'Subscription'), ('transfer', 'Transfer')], default='subscription', max_length=50)),
                ('device_price', models.FloatField(default=0)),
                ('device_discount', models.FloatField(default=0)),
                ('device_sell_price', models.FloatField(default=0)),
                ('subscription_price', models.FloatField(default=0)),
                ('subscription_discount', models.FloatField(default=0)),
                ('subscription_sell_price', models.FloatField(default=0)),
                ('plan_price', models.FloatField(default=0)),
                ('device_transfer_price', models.FloatField(default=0)),
                ('device_transfer_discount', models.FloatField(default=0)),
                ('device_transfer_sell_price', models.FloatField(default=0)),
                ('duration_days', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('in_active', 'in_active')], default='active', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_cart',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCartWithSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subscription_cart_with_site',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=150)),
                ('feature_status', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_feature',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('invoice_type', models.CharField(choices=[('Performa Invoice', 'Performa Invoice'), ('Commercial Invoice', 'Commercial Invoice')], default='Performa Invoice', max_length=50)),
                ('quantity', models.FloatField(default=1)),
                ('sell_price', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('gst_rate', models.FloatField(default=18)),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(null=True)),
                ('sgst', models.FloatField(default=0)),
                ('cgst', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('payment_reference_id', models.CharField(max_length=150, null=True)),
                ('check_out_url', models.CharField(max_length=750, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subscription_invoice',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('check_out_url', models.URLField(blank=True, null=True)),
                ('invoice_no', models.CharField(max_length=50)),
                ('active', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('razor_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('subtotal', models.FloatField(default=0)),
                ('cgst_amount', models.FloatField(default=0)),
                ('sgst_amount', models.FloatField(default=0)),
                ('igst_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_method_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'payment_subscription',
            },
        ),
        migrations.CreateModel(
            name='PaymentGSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('payment_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='subscription.paymentsubscription')),
            ],
            options={
                'db_table': 'payment_gst_details',
            },
        ),
        migrations.CreateModel(
            name='PaymentSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('subscription_type', models.CharField(max_length=50)),
                ('device_price', models.FloatField(default=0)),
                ('subscription_price', models.FloatField(default=0)),
                ('device_amount', models.FloatField(default=0)),
                ('subscription_amount', models.FloatField(default=0)),
                ('plan_total', models.FloatField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscription.paymentsubscription')),
            ],
            options={
                'db_table': 'payment_subscription_item',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RenewalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_carts', to='company.company')),
            ],
            options={
                'db_table': 'renewal_cart',
            },
        ),
    ]
