# Generated by Django 5.2.5 on 2026-04-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentsubscriptionitem",
            name="device_amount",
        ),
        migrations.RemoveField(
            model_name="paymentsubscriptionitem",
            name="device_price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_discount",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_sell_price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_transfer_discount",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_transfer_price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="device_transfer_sell_price",
        ),
    ]
