# Generated by Django 6.0.3 on 2026-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0003_remove_paymentsubscriptionitem_payment_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.IntegerField(db_column="subscription_price"),
        ),
    ]
