# Generated by Django 6.0.3 on 2026-04-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_subscription_price"),
        ("subscription", "0004_discount"),
    ]

    operations = []
