# Generated by Django 5.2.5 on 2026-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsubscription",
            name="promocode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
