# Generated by Django 5.2.5 on 2026-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_paymentsubscription_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionfeature",
            name="feature_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Unique code for feature",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionfeature",
            name="is_unlimited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionfeature",
            name="value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionfeature",
            name="feature_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Feature Name"
            ),
        ),
    ]
