# Generated by Django 5.2.5 on 2026-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0009_alter_discount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="featureusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentsubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionfeature",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
