# Generated by Django 6.0.3 on 2026-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0017_drop_token_override_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionfeature",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="True for system flat-field features that should not appear in core_features/subscription_feature arrays",
            ),
        ),
    ]
