# Generated by Django 6.0.3 on 2026-07-22 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0018_add_is_hidden_to_subscriptionfeature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="ai_chat_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="career_compare",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="career_roadmap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="course_portal_access_type",
            field=models.CharField(
                choices=[("full", "Full"), ("limited", "Limited")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="internship_access_type",
            field=models.CharField(
                choices=[("full", "Full"), ("limited", "Limited")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="job_portal_access_type",
            field=models.CharField(
                choices=[("full", "Full"), ("limited", "Limited")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_course_portal_access",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_internship_access",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_job_portal_access",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_profile_assessment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_project_topic_access",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="no_of_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="project_topic_access_type",
            field=models.CharField(
                choices=[("full", "Full"), ("limited", "Limited")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
