# Generated by Django 6.0.3 on 2026-07-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0019_subscription_ai_chat_access_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionfeature",
            name="is_core",
        ),
        migrations.RemoveField(
            model_name="subscriptionfeature",
            name="is_hidden",
        ),
        migrations.RemoveField(
            model_name="subscriptionfeature",
            name="is_unlimited",
        ),
        migrations.RemoveField(
            model_name="subscriptionfeature",
            name="value",
        ),
    ]
