# Generated by Django 6.0.3 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseGenerationPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Course Generation",
                "verbose_name_plural": "AI Course Generation",
                "managed": False,
            },
        ),
    ]
