# Generated by Django 6.0.3 on 2026-07-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursegenerationpanel",
            options={
                "managed": False,
                "permissions": [("generate_course", "Can generate AI course details")],
                "verbose_name": "AI Course Generation",
                "verbose_name_plural": "AI Course Generation",
            },
        ),
    ]
