# Generated by Django 6.0.3 on 2026-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EndClient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "profile_photo",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=25, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "end_client",
            },
        ),
    ]
