# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endclient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_client_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endclient',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_client_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endclient',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_client_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
