# Generated by Django 5.2.5 on 2026-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerrecommendation",
            name="raw_ai_response",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
