# Generated by Django 5.2.5 on 2026-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0002_alter_careerrecommendation_raw_ai_response"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careerrecommendationsuggestion",
            old_name="career_factor",
            new_name="career_factors",
        ),
        migrations.RemoveField(
            model_name="careerrecommendationsuggestion",
            name="easy_decision_making",
        ),
        migrations.AddField(
            model_name="careerrecommendation",
            name="easy_decision_making",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="careerrecommendationsuggestion",
            name="career_roadmap",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="careerrecommendationsuggestion",
            name="required_education",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
