# Generated by Django 5.2.5 on 2026-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_career",
            "0003_rename_career_factor_careerrecommendationsuggestion_career_factors_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="careerrecommendation",
            name="last_recommended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
