# Generated by Django 5.2.5 on 2026-05-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_alter_studentassessment_updated_at"),
        ("assessment_career", "0004_careerrecommendation_last_recommended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerrecommendation",
            name="assessment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_recommendation",
                to="assessment.studentassessment",
            ),
        ),
    ]
