# Generated by Django 5.2.5 on 2026-05-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0005_alter_careerrecommendation_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerrecommendation",
            name="last_recommended_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="careerrecommendationsuggestion",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
