# Generated by Django 6.0.3 on 2026-06-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_parentassessment_child'),
        ('assessment_career', '0008_parent_career_recommendation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerrecommendationchatsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationchatsession',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationchatsession',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationchatsession',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationsuggestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationsuggestion',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationsuggestion',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='careerrecommendationsuggestion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendation',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendation',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationsuggestion',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatmessage',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatmessage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatsession',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatsession',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationchatsession',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationsuggestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationsuggestion',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='parentcareerrecommendationsuggestion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='assessment',
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='parent_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_recommendation', to='assessment.parentassessment'),
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='profile_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('working_professional', 'Working Professional')], default='student', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='student_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_recommendation', to='assessment.studentassessment'),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CareerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('career_name', models.CharField(blank=True, max_length=250, null=True)),
                ('match_percentage', models.PositiveIntegerField()),
                ('ai_insight', models.TextField()),
                ('why_this_career', models.JSONField(blank=True, default=list)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('required_education', models.JSONField(blank=True, default=dict)),
                ('career_factors', models.JSONField(blank=True, default=list)),
                ('career_roadmap', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='assessment_career.careerrecommendation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_suggestion',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='assessment_career.careersuggestion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_chat_session',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assessment_career.chatsession')),
            ],
            options={
                'db_table': 'career_chat_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CareerRecommendationChatMessage',
        ),
        migrations.DeleteModel(
            name='CareerRecommendationChatSession',
        ),
        migrations.DeleteModel(
            name='CareerRecommendationSuggestion',
        ),
        migrations.DeleteModel(
            name='ParentCareerRecommendation',
        ),
        migrations.DeleteModel(
            name='ParentCareerRecommendationChatMessage',
        ),
        migrations.DeleteModel(
            name='ParentCareerRecommendationChatSession',
        ),
        migrations.DeleteModel(
            name='ParentCareerRecommendationSuggestion',
        ),
    ]
