# Generated by Django 6.0.3 on 2026-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_career",
            "0009_remove_careerrecommendationchatsession_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerrecommendation",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("working_professional", "Working Professional"),
                ],
                default="student",
                max_length=30,
            ),
        ),
    ]
