# Generated by Django 6.0.3 on 2026-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0010_alter_careerrecommendation_profile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersuggestion",
            name="career_factors",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
