# Generated by Django 6.0.3 on 2026-06-26 11:16

from django.db import migrations


def backfill_chat_session_child(apps, schema_editor):
    ChatSession = apps.get_model("assessment_career", "ChatSession")
    CareerSuggestion = apps.get_model("assessment_career", "CareerSuggestion")
    CareerRecommendation = apps.get_model("assessment_career", "CareerRecommendation")
    ParentAssessment = apps.get_model("assessment", "ParentAssessment")

    for session in ChatSession.objects.filter(child_id__isnull=True).select_related("suggestion__recommendation"):
        rec = session.suggestion.recommendation
        if rec.profile_type == "parent" and rec.parent_assessment_id is not None:
            try:
                pa = ParentAssessment.objects.only("child_id").get(id=rec.parent_assessment_id)
                if pa.child_id is not None:
                    ChatSession.objects.filter(id=session.id).update(child_id=pa.child_id)
            except ParentAssessment.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_career", "0013_add_child_to_chat_session"),
    ]

    operations = [
        migrations.RunPython(backfill_chat_session_child, reverse_code=migrations.RunPython.noop),
    ]
