# Generated by Django 6.0.3 on 2026-03-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("city_areas", "0001_initial"),
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityarea",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="country.country",
            ),
        ),
    ]
