# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_areas', '0002_initial'),
        ('state', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cityarea',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_area_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityarea',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_area_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityarea',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_areas_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='cityarea',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_area_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
