from __future__ import annotations

from pydantic import BaseModel, Field, field_validator, model_validator


class ProjectItem(BaseModel):
    """A single personal project generated by AI."""

    project_name: str = Field(min_length=3, max_length=200)
    description: str = Field(min_length=30, max_length=1000)
    difficulty: str = Field(min_length=3, max_length=50)
    duration: str = Field(min_length=3, max_length=50)
    technology_stack: list[str] = Field(min_length=1, max_length=20)
    skills: list[str] = Field(min_length=1, max_length=20)
    features: list[str] = Field(min_length=1, max_length=20)
    career_match_percentage: int = Field(ge=80, le=100)

    @field_validator("project_name", "description", "difficulty", "duration", mode="before")
    @classmethod
    def _strip_strings(cls, value: object) -> str:
        return str(value or "").strip()

    @field_validator("technology_stack", "skills", "features", mode="before")
    @classmethod
    def _coerce_lists(cls, value: object) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            text = value.strip()
            if not text:
                return []
            for sep in ("\n", ";", "|"):
                if sep in text:
                    return [p.strip() for p in text.split(sep) if p.strip()]
            if "," in text:
                return [p.strip() for p in text.split(",") if p.strip()]
            return [text]
        if isinstance(value, (list, tuple)):
            out: list[str] = []
            for item in value:
                if item is None:
                    continue
                if isinstance(item, dict):
                    text = str(
                        item.get("text") or item.get("name") or item.get("label") or ""
                    ).strip()
                else:
                    text = str(item).strip()
                if text:
                    out.append(text)
            return out
        return [str(value).strip()] if str(value).strip() else []

    @model_validator(mode="after")
    def _normalize_and_deduplicate(self) -> ProjectItem:
        for field_name in ("technology_stack", "skills", "features"):
            items = [item.strip() for item in getattr(self, field_name) if item.strip()]
            seen: set[str] = set()
            deduped: list[str] = []
            for item in items:
                key = item.casefold()
                if key not in seen:
                    seen.add(key)
                    deduped.append(item)
            setattr(self, field_name, deduped)
        return self


class ProjectRecommendationPayload(BaseModel):
    """Top-level AI response for project recommendations."""

    projects: list[ProjectItem] = Field(min_length=3, max_length=3)
