from __future__ import annotations

from pydantic import BaseModel, Field, field_validator, model_validator


_DIFFICULTY_VALUES = frozenset({"Beginner", "Intermediate", "Advanced"})


class ProjectItem(BaseModel):
    """A single portfolio project generated by AI."""

    project_name: str = Field(min_length=3, max_length=200)
    short_description: str = Field(min_length=30, max_length=1000)
    difficulty: str = Field(min_length=3, max_length=50)
    estimated_duration: str = Field(min_length=3, max_length=100)
    industry_relevance: str = Field(min_length=10)
    skills_gained: list[str] = Field(min_length=5, max_length=5)
    deliverables: list[str] = Field(min_length=5, max_length=5)
    portfolio_value: str = Field(min_length=10)
    why_this_project: str = Field(min_length=10)

    _STRING_FIELDS = (
        "project_name",
        "short_description",
        "difficulty",
        "estimated_duration",
        "industry_relevance",
        "portfolio_value",
        "why_this_project",
    )
    _LIST_FIELDS = (
        "skills_gained",
        "deliverables",
    )

    @field_validator(*_STRING_FIELDS, mode="before")
    @classmethod
    def _strip_strings(cls, value: object) -> str:
        return str(value or "").strip()

    @field_validator(*_LIST_FIELDS, mode="before")
    @classmethod
    def _coerce_lists(cls, value: object) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            text = value.strip()
            if not text:
                return []
            for sep in ("\n", ";", "|"):
                if sep in text:
                    return [p.strip() for p in text.split(sep) if p.strip()]
            if "," in text:
                return [p.strip() for p in text.split(",") if p.strip()]
            return [text]
        if isinstance(value, (list, tuple)):
            out: list[str] = []
            for item in value:
                if item is None:
                    continue
                if isinstance(item, dict):
                    text = str(
                        item.get("text") or item.get("name") or item.get("label") or ""
                    ).strip()
                else:
                    text = str(item).strip()
                if text:
                    out.append(text)
            return out
        return [str(value).strip()] if str(value).strip() else []

    @field_validator("difficulty")
    @classmethod
    def _validate_difficulty(cls, value: str) -> str:
        stripped = value.strip()
        if stripped not in _DIFFICULTY_VALUES:
            raise ValueError(
                f"difficulty must be one of {sorted(_DIFFICULTY_VALUES)}, got '{stripped}'"
            )
        return stripped

    @model_validator(mode="after")
    def _normalize_and_deduplicate(self) -> ProjectItem:
        for field_name in self._LIST_FIELDS:
            items = [item.strip() for item in getattr(self, field_name) if item.strip()]
            seen: set[str] = set()
            deduped: list[str] = []
            for item in items:
                key = item.casefold()
                if key not in seen:
                    seen.add(key)
                    deduped.append(item)
            setattr(self, field_name, deduped)
        return self


class ProjectRecommendationPayload(BaseModel):
    """Top-level AI response for portfolio project recommendations."""

    projects: list[ProjectItem] = Field(min_length=3, max_length=3)
