# Generated by Django 5.2.1 on 2026-03-24 11:31

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education_level", "0002_fix_legacy_is_archived_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='stream.streamimportbatch')),
            ],
            options={
                'db_table': 'stream_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream_code', models.CharField(max_length=64)),
                ('stream_name', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField(unique=True)),
                ('parent_safe_label', models.BooleanField(default=False)),
                ('traditional_equivalent', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='education_level.educationlevel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream',
                'ordering': ['sequence_order', 'stream_name'],
                'indexes': [models.Index(fields=['stream_code'], name='stream_stream__d76666_idx'), models.Index(fields=['sequence_order'], name='stream_sequenc_2f1e97_idx'), models.Index(fields=['is_active'], name='stream_is_acti_c3a521_idx'), models.Index(fields=['deleted'], name='stream_deleted_dc5c5c_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('stream_code'), name='stream_stream_code_ci_uniq')],
            },
        ),
    ]
