# Generated by Django 6.0.3 on 2026-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="parent_safe_label",
        ),
    ]
