# Generated by Django 6.0.3 on 2026-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0003_remove_stream_parent_safe_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="traditional_equivalent",
        ),
    ]
