# Generated by Django 6.0.3 on 2026-03-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_career_mapping", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="domaincareermapping",
            new_name="domain_care_domain__497bf9_idx",
            old_name="domain_care_domain_i_9f0b6b_idx",
        ),
        migrations.RenameIndex(
            model_name="domaincareermapping",
            new_name="domain_care_career__7d95c4_idx",
            old_name="domain_care_career__56a2f9_idx",
        ),
        migrations.RenameIndex(
            model_name="domaincareermapping",
            new_name="domain_care_weight__48212f_idx",
            old_name="domain_care_weight__ff3f12_idx",
        ),
        migrations.RenameIndex(
            model_name="domaincareermapping",
            new_name="domain_care_is_acti_07fcf4_idx",
            old_name="domain_care_is_acti_4f1f42_idx",
        ),
        migrations.RenameIndex(
            model_name="domaincareermapping",
            new_name="domain_care_deleted_cd1247_idx",
            old_name="domain_care_deleted_fa3b0b_idx",
        ),
    ]
