# Generated by Django 5.2.5 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "domain_career_mapping",
            "0002_rename_domain_care_domain_i_9f0b6b_idx_domain_care_domain__497bf9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaincareermapping",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
