JOB_OVERVIEW_MIN_LENGTH = 10
JOB_OVERVIEW_MAX_LENGTH = 1000
OPTIONAL_FIELD_MAX_LENGTH = 250
JOB_TITLE_MAX_LENGTH = 200

# UI card length targets (Add Job form)
DESCRIPTION_MIN_WORDS = 20
DESCRIPTION_MAX_WORDS = 40
DESCRIPTION_SENTENCE_COUNT = 2

RESPONSIBILITIES_COUNT = 5
RESPONSIBILITY_ITEM_MIN_WORDS = 5
RESPONSIBILITY_ITEM_MAX_WORDS = 10

WHY_THIS_MATCH_MIN_WORDS = 15
WHY_THIS_MATCH_MAX_WORDS = 35
WHY_THIS_MATCH_SENTENCE_COUNT = 2

EDUCATION_TAGS_MIN = 1
EDUCATION_TAGS_MAX = 4
EDUCATION_TAG_MAX_LENGTH = 80

DISALLOWED_PLACEHOLDERS = (
    "tbd",
    "n/a",
    "<placeholder>",
    "null",
)
