# Generated by Django 6.0.3 on 2026-08-03 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0041_professionalassessment_professiona_user_id_09e9be_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecommendationPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AI Project Recommendation',
                'verbose_name_plural': 'AI Project Recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('profile_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('working_professional', 'Working Professional')], default='student', max_length=30)),
                ('domain', models.CharField(blank=True, default='', max_length=250)),
                ('domain_category', models.CharField(blank=True, default='', max_length=250)),
                ('education_level', models.CharField(blank=True, default='', max_length=150)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('last_recommended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent_assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_recommendation', to='assessment.parentassessment')),
                ('professional_assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_recommendation', to='assessment.professionalassessment')),
                ('student_assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_recommendation', to='assessment.studentassessment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
