# Generated by Django 6.0.3 on 2026-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectRecommendationPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Project Recommendation",
                "verbose_name_plural": "AI Project Recommendation",
                "managed": False,
            },
        ),
    ]
