# Generated by Django 6.0.3 on 2026-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrecommendation',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
