# Generated by Django 6.0.3 on 2026-08-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_recommendation', '0002_projectrecommendation_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrecommendation',
            name='parent_assessment',
        ),
        migrations.RemoveField(
            model_name='projectrecommendation',
            name='professional_assessment',
        ),
        migrations.RemoveField(
            model_name='projectrecommendation',
            name='student_assessment',
        ),
    ]
