# Generated by Django 6.0.3 on 2026-08-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_recommendation', '0003_remove_projectrecommendation_parent_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrecommendation',
            name='education_level',
        ),
    ]
