# Generated by Django 6.0.3 on 2026-08-06 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_recommendation', '0004_remove_projectrecommendation_education_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualProjectImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_project_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_project_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualProjectImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='project_recommendation.manualprojectimportbatch')),
            ],
            options={
                'db_table': 'manual_project_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], default='ai', help_text='AI: LLM-generated projects. Manual: projects served from the ManualProject database table.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_recommendation_config_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Recommendation Configuration',
                'verbose_name_plural': 'Project Recommendation Configuration',
                'db_table': 'project_recommendation_config',
            },
        ),
        migrations.CreateModel(
            name='ManualProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, default='', max_length=250)),
                ('domain_category', models.CharField(blank=True, default='', max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('estimated_duration', models.CharField(blank=True, default='', max_length=100)),
                ('industry_relevance', models.TextField(blank=True, default='')),
                ('portfolio_value', models.TextField(blank=True, default='')),
                ('why_this_project', models.TextField(blank=True, default='')),
                ('skills_gained', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_project',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['domain', 'domain_category', 'is_active'], name='manual_proj_domain_bfe8aa_idx'), models.Index(fields=['is_active'], name='manual_proj_is_acti_a26d0f_idx')],
            },
        ),
    ]
