# Generated by Django 6.0.3 on 2026-08-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_recommendation', '0005_manualprojectimportbatch_manualprojectimporterror_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manualproject',
            name='manual_proj_domain_bfe8aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='manualproject',
            name='manual_proj_is_acti_a26d0f_idx',
        ),
        migrations.RemoveField(
            model_name='manualprojectimporterror',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='projectrecommendationconfig',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='manualproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='manualproject',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='manualproject',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ManualProjectImportBatch',
        ),
        migrations.DeleteModel(
            name='ManualProjectImportError',
        ),
        migrations.DeleteModel(
            name='ProjectRecommendationConfig',
        ),
        migrations.DeleteModel(
            name='ManualProject',
        ),
    ]
