# Generated by Django 6.0.3 on 2026-06-03 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("city", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("education_tags", models.JSONField(blank=True, default=list)),
                ("why_this_match", models.TextField(blank=True, null=True)),
                (
                    "internship_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("paid", "Paid"),
                            ("stipend", "Stipend"),
                        ],
                        default="free",
                        max_length=150,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="offline",
                        max_length=150,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "fees_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stipend_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("certificate_provided", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "internship",
                "ordering": ["-created_at"],
            },
        ),
    ]
