# Generated by Django 6.0.3 on 2026-06-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="education_tags",
        ),
    ]
