# Generated by Django 6.0.3 on 2026-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0005_alter_educationlevel_updated_at"),
        ("internship_job", "0003_internship_education_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="education_tags",
            field=models.ManyToManyField(
                blank=True, to="education_level.educationlevel"
            ),
        ),
    ]
