# Generated by Django 6.0.3 on 2026-06-09 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def create_table_if_not_exists(apps, schema_editor):
    if "internship_application" not in connection.introspection.table_names():
        schema_editor.create_model(apps.get_model("internship_job", "InternshipApplication"))


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0004_alter_internship_education_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="InternshipApplication",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                        (
                            "updated_at",
                            models.DateTimeField(blank=True, db_index=True, null=True),
                        ),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        ("deleted", models.BooleanField(default=False)),
                        ("resume", models.CharField(blank=True, max_length=450, null=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("applied", "Applied"),
                                    ("under_review", "Under_Review"),
                                    ("selected", "Selected"),
                                    ("rejected", "Rejected"),
                                ],
                                default="applied",
                                max_length=100,
                            ),
                        ),
                        ("applied_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_created",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "deleted_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_deleted",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "internship",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="internship_applications",
                                to="internship_job.internship",
                            ),
                        ),
                        (
                            "student",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="student_internship_applications",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "updated_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(class)s_updated",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "internship_application",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_table_if_not_exists, migrations.RunPython.noop),
            ],
        ),
    ]
