# Generated by Django 6.0.3 on 2026-06-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0005_internshipapplication"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        ),
    ]
