# Generated by Django 6.0.3 on 2026-06-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0006_alter_internshipapplication_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internshipapplication",
            name="student",
        ),
    ]
