# Generated by Django 6.0.3 on 2026-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0008_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="active",
                max_length=100,
            ),
        ),
    ]
