# Generated by Django 6.0.3 on 2026-06-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0008_internshipapplication_applicant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internshipapplication",
            name="resume",
        ),
    ]
