# Generated by Django 6.0.3 on 2026-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0009_remove_internshipapplication_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="resume",
            field=models.CharField(default="", max_length=450),
        ),
    ]
