# Generated by Django 6.0.3 on 2026-06-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0010_jobapplication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="Job",
            new_name="job",
        ),
    ]
