# Generated by Django 6.0.3 on 2026-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0011_alter_internshipapplication_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internshipapplication",
            name="resume",
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
