# Generated by Django 6.0.3 on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0066_professionalprofile_referred_by_and_more"),
        ("internship_job", "0011_rename_job_jobapplication_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="organization_name",
        ),
        migrations.AddField(
            model_name="job",
            name="corporate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user_profile.corporateprofile",
            ),
        ),
    ]
