# Generated by Django 6.0.3 on 2026-07-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0013_job_country_job_job_overview_job_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
    ]
