# Generated by Django 6.0.3 on 2026-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0014_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Application deadline date", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Application deadline date", null=True
            ),
        ),
    ]
