# Generated by Django 6.0.3 on 2026-07-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0015_internship_application_deadline_and_more"),
        ("user_profile", "0066_professionalprofile_referred_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="organization_name",
        ),
        migrations.AddField(
            model_name="internship",
            name="corporate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corporate_internships",
                to="user_profile.corporateprofile",
            ),
        ),
    ]
