# Generated by Django 6.0.3 on 2026-07-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0018_internship_provider_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department or division for this internship.",
                max_length=250,
                null=True,
            ),
        ),
    ]
