# Generated by Django 6.0.3 on 2026-07-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0020_add_status_to_internship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="corporate",
        ),
    ]
