# Generated by Django 6.0.3 on 2026-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_job', '0021_remove_internship_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='internship_overview',
            field=models.TextField(blank=True, help_text='Employer-provided internship overview used as AI generation context.', null=True),
        ),
    ]
