# Generated by Django 6.0.3 on 2026-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_job", "0022_add_internship_overview_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="provider",
        ),
    ]
