# Generated by Django 6.0.3 on 2026-08-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_job', '0027_internshipapplicationnote_jobapplicationnote'),
        ('internship_job', '0027_recreate_job_application_table'),
    ]

    operations = [
    ]
