# Generated by Django 6.0.3 on 2026-03-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domain", "0002_initial"),
        ("skill", "0002_initial"),
        ("domain_skill_mapping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="domainskillmapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domainskillmapping",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domainskillmapping",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_skill_mappings",
                to="domain.domain",
            ),
        ),
        migrations.AddField(
            model_name="domainskillmapping",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_skill_mappings",
                to="skill.skill",
            ),
        ),
        migrations.AddField(
            model_name="domainskillmapping",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domainskillmappingimportbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_skill_mapping_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domainskillmappingimporterror",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_rows",
                to="domain_skill_mapping.domainskillmappingimportbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="domainskillmapping",
            index=models.Index(fields=["domain"], name="domain_ski_domain__idx"),
        ),
        migrations.AddIndex(
            model_name="domainskillmapping",
            index=models.Index(fields=["skill"], name="domain_ski_skill__idx"),
        ),
        migrations.AddIndex(
            model_name="domainskillmapping",
            index=models.Index(fields=["weight_score"], name="domain_ski_weight__idx"),
        ),
        migrations.AddIndex(
            model_name="domainskillmapping",
            index=models.Index(fields=["is_active"], name="domain_ski_is_act_idx"),
        ),
        migrations.AddIndex(
            model_name="domainskillmapping",
            index=models.Index(fields=["deleted"], name="domain_ski_deleted_idx"),
        ),
        migrations.AddConstraint(
            model_name="domainskillmapping",
            constraint=models.UniqueConstraint(
                fields=("domain", "skill"),
                name="domain_skill_mapping_domain_skill_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="domainskillmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_score__gte", 0), ("weight_score__lte", 100)
                ),
                name="domain_skill_mapping_weight_score_0_100_ck",
            ),
        ),
    ]
