# Generated by Django 5.2.5 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "domain_skill_mapping",
            "0003_rename_domain_ski_domain__idx_domain_skil_domain__8d6fbd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainskillmapping",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
