# Generated by Django 5.2.5 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_category", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscategory",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
