# Generated by Django 6.0.3 on 2026-07-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship_generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internshipgenerationpanel",
            options={
                "managed": False,
                "permissions": [
                    ("generate_internship", "Can generate AI internship details")
                ],
                "verbose_name": "AI Internship Generation",
                "verbose_name_plural": "AI Internship Generation",
            },
        ),
    ]
