# Generated by Django 5.2.1 on 2026-03-23 06:15

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='domain.domainimportbatch')),
            ],
            options={
                'db_table': 'domain_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_code', models.CharField(max_length=64)),
                ('domain_name', models.CharField(max_length=255)),
                ('parent_acceptance_level', models.PositiveSmallIntegerField()),
                ('future_relevance_score', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_domains', to='domain.domain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain',
                'indexes': [models.Index(fields=['domain_code'], name='domain_domain__c9a31b_idx'), models.Index(fields=['is_active'], name='domain_is_acti_d8acfe_idx'), models.Index(fields=['is_archived'], name='domain_is_arch_f1d5ad_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('domain_code'), name='domain_domain_code_ci_uniq')],
            },
        ),
    ]
