# Generated by Cursor on 2026-04-01

from django.db import migrations


# One-time seed from the previously hardcoded affinity map.
# This keeps recommendation scoring consistent after moving weights to the DB.
DOMAIN_AFFINITY = {
    "ai_data": {"interest": 0.20, "aptitude": 0.50, "personality": 0.10, "work_style": 0.20},
    "data_engineering": {"interest": 0.15, "aptitude": 0.55, "personality": 0.10, "work_style": 0.20},
    "cybersecurity": {"interest": 0.20, "aptitude": 0.50, "personality": 0.15, "work_style": 0.15},
    "cloud_computing": {"interest": 0.15, "aptitude": 0.50, "personality": 0.10, "work_style": 0.25},
    "devops": {"interest": 0.15, "aptitude": 0.45, "personality": 0.10, "work_style": 0.30},
    "quantum": {"interest": 0.20, "aptitude": 0.60, "personality": 0.10, "work_style": 0.10},
    "nanotech": {"interest": 0.25, "aptitude": 0.55, "personality": 0.10, "work_style": 0.10},
    "blockchain": {"interest": 0.20, "aptitude": 0.50, "personality": 0.10, "work_style": 0.20},
    "robotics": {"interest": 0.25, "aptitude": 0.45, "personality": 0.10, "work_style": 0.20},
    "ev_mobility": {"interest": 0.25, "aptitude": 0.40, "personality": 0.10, "work_style": 0.25},
    "manufacturing": {"interest": 0.20, "aptitude": 0.35, "personality": 0.15, "work_style": 0.30},
    "energy_storage": {"interest": 0.20, "aptitude": 0.45, "personality": 0.10, "work_style": 0.25},
    "renewable_energy": {"interest": 0.25, "aptitude": 0.40, "personality": 0.15, "work_style": 0.20},
    "space_tech": {"interest": 0.30, "aptitude": 0.50, "personality": 0.10, "work_style": 0.10},
    "iot": {"interest": 0.25, "aptitude": 0.45, "personality": 0.10, "work_style": 0.20},
    "construction_tech": {"interest": 0.20, "aptitude": 0.35, "personality": 0.15, "work_style": 0.30},
    "urban_tech": {"interest": 0.25, "aptitude": 0.40, "personality": 0.15, "work_style": 0.20},
    "water_tech": {"interest": 0.25, "aptitude": 0.40, "personality": 0.15, "work_style": 0.20},
    "healthtech": {"interest": 0.30, "aptitude": 0.35, "personality": 0.25, "work_style": 0.10},
    "biotech": {"interest": 0.25, "aptitude": 0.45, "personality": 0.20, "work_style": 0.10},
    "pharma": {"interest": 0.25, "aptitude": 0.45, "personality": 0.20, "work_style": 0.10},
    "med_devices": {"interest": 0.25, "aptitude": 0.40, "personality": 0.25, "work_style": 0.10},
    "mental_health": {"interest": 0.30, "aptitude": 0.20, "personality": 0.40, "work_style": 0.10},
    "fintech": {"interest": 0.25, "aptitude": 0.40, "personality": 0.15, "work_style": 0.20},
    "ecommerce": {"interest": 0.30, "aptitude": 0.30, "personality": 0.20, "work_style": 0.20},
    "supply_chain": {"interest": 0.20, "aptitude": 0.35, "personality": 0.15, "work_style": 0.30},
    "insurance_tech": {"interest": 0.20, "aptitude": 0.40, "personality": 0.20, "work_style": 0.20},
    "hrtech": {"interest": 0.25, "aptitude": 0.25, "personality": 0.35, "work_style": 0.15},
    "climate_tech": {"interest": 0.35, "aptitude": 0.35, "personality": 0.15, "work_style": 0.15},
    "agritech": {"interest": 0.30, "aptitude": 0.35, "personality": 0.15, "work_style": 0.20},
    "ar_vr": {"interest": 0.40, "aptitude": 0.30, "personality": 0.20, "work_style": 0.10},
    "gaming": {"interest": 0.40, "aptitude": 0.35, "personality": 0.15, "work_style": 0.10},
    "creator_economy": {"interest": 0.45, "aptitude": 0.15, "personality": 0.30, "work_style": 0.10},
    "digital_marketing": {"interest": 0.40, "aptitude": 0.25, "personality": 0.25, "work_style": 0.10},
    "marketing": {"interest": 0.40, "aptitude": 0.20, "personality": 0.30, "work_style": 0.10},
    "edtech": {"interest": 0.35, "aptitude": 0.25, "personality": 0.30, "work_style": 0.10},
    "legaltech": {"interest": 0.25, "aptitude": 0.40, "personality": 0.25, "work_style": 0.10},
    "ai_ethics": {"interest": 0.30, "aptitude": 0.35, "personality": 0.25, "work_style": 0.10},
    "traveltech": {"interest": 0.40, "aptitude": 0.20, "personality": 0.30, "work_style": 0.10},
    "foodtech": {"interest": 0.35, "aptitude": 0.25, "personality": 0.25, "work_style": 0.15},
    "fashiontech": {"interest": 0.45, "aptitude": 0.15, "personality": 0.30, "work_style": 0.10},
    "sports_tech": {"interest": 0.40, "aptitude": 0.25, "personality": 0.25, "work_style": 0.10},
    "defense_tech": {"interest": 0.25, "aptitude": 0.35, "personality": 0.20, "work_style": 0.20},
}


def forwards(apps, schema_editor):
    Domain = apps.get_model("domain", "Domain")
    for code, w in DOMAIN_AFFINITY.items():
        Domain.objects.filter(domain_code__iexact=code).update(
            interest_weight=w["interest"],
            aptitude_weight=w["aptitude"],
            personality_weight=w["personality"],
            work_style_weight=w["work_style"],
        )


def backwards(apps, schema_editor):
    Domain = apps.get_model("domain", "Domain")
    codes = list(DOMAIN_AFFINITY.keys())
    Domain.objects.filter(domain_code__in=codes).update(
        interest_weight=None,
        aptitude_weight=None,
        personality_weight=None,
        work_style_weight=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_domain_affinity_weights"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

