# Generated by Django 6.0.3 on 2026-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_seed_domain_affinity_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='suggested_degrees',
            field=models.CharField(blank=True, help_text='Comma-separated degree suggestions for this domain (e.g. B.Tech CS, BSc AI).', max_length=500),
        ),
    ]
