# Generated by Django 6.0.3 on 2026-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0005_add_suggested_degrees"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="counselor_note",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly reason shown to students (e.g. 'You seem to enjoy solving real-world problems - this field is built for that').",
                max_length=300,
            ),
        ),
    ]
