# Generated by Django 6.0.3 on 2026-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0008_alter_streamreportmeta_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaincounsellorknowledge",
            name="domain_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Domain/soft skill keywords for this domain e.g. ['data analysis','research']",
            ),
        ),
        migrations.AddField(
            model_name="domaincounsellorknowledge",
            name="technical_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Technical skill keywords for this domain e.g. ['python','sql','machine learning']",
            ),
        ),
    ]
