# Generated by Django 5.2.5 on 2026-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0013_domain_category_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="domain_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload domain image/icon",
                null=True,
                upload_to="domain_images/",
            ),
        ),
    ]
