# Generated by Django 6.0.3 on 2026-05-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_remove_domain_aptitude_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_category',
        ),
    ]
