# Generated by Django 5.2.5 on 2026-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0016_remove_domain_domain_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain_image",
            field=models.CharField(
                blank=True,
                help_text="Upload domain image/icon",
                max_length=250,
                null=True,
            ),
        ),
    ]
