# Generated by Django 6.0.3 on 2026-03-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_category', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('photo_file', models.CharField(max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_photo',
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_service',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.CharField(max_length=250, null=True)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_type', models.CharField(blank=True, choices=[('Media owner', 'Media owner'), ('Advertisers', 'Advertisers')], max_length=25, null=True)),
                ('gst_no_verified', models.BooleanField(default=False)),
                ('gst_address_building', models.CharField(max_length=150, null=True)),
                ('gst_address_landmark', models.CharField(max_length=100, null=True)),
                ('gst_address_pincode', models.IntegerField(null=True)),
                ('communication_address_building', models.CharField(max_length=150, null=True)),
                ('communication_address_landmark', models.CharField(max_length=100, null=True)),
                ('communication_address_pincode', models.IntegerField(null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('pinterest_url', models.URLField(blank=True, null=True)),
                ('year_of_establishment', models.IntegerField(default=0)),
                ('number_of_employees', models.CharField(choices=[('1-10 employees', '1-10 employees'), ('11-50 employees', '11-50 employees'), ('51-200 employees', '51-200 employees'), ('201-500 employees', '201-500 employees'), ('501-1000 employees', '501-1000 employees'), ('1001-5000 employees', '1001-5000 employees'), ('5001-10000 employees', '5001-10000 employees'), ('10000 + employees', '10000 + employees')], default='1-10 employees', max_length=25)),
                ('monday_friday_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('saturday_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('sunday_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=25)),
                ('is_active', models.BooleanField(default=False)),
                ('active_subscription', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('days_to_expire', models.IntegerField(default=0)),
                ('is_request_demo', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='business_category.businesscategory')),
                ('communication_address_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_address_companies', to='city.city')),
            ],
        ),
    ]
