# Generated by Django 5.2.5 on 2026-03-18 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment_name", models.CharField(max_length=50, null=True)),
                ("attachment_file", models.CharField(max_length=250, null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "attachment",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("website", models.CharField(max_length=100, null=True)),
                (
                    "no_of_employees",
                    models.CharField(
                        choices=[
                            ("1-10 employees", "1-10 employees"),
                            ("11-50 employees", "11-50 employees"),
                            ("51-200 employees", "51-200 employees"),
                            ("201-500 employees", "201-500 employees"),
                            ("501-1000 employees", "501-1000 employees"),
                            ("1001-5000 employees", "1001-5000 employees"),
                            ("5001-10000 employees", "5001-10000 employees"),
                            ("10000 + employees", "10000 + employees"),
                        ],
                        default="1-10 employees",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[("Buyer", "Buyer"), ("Seller", "Seller")],
                        default="Buyer",
                        max_length=25,
                    ),
                ),
                ("company_pan", models.CharField(max_length=10, null=True)),
                ("company_pan_verified", models.BooleanField(default=False)),
                ("gst_no", models.CharField(max_length=15, null=True)),
                ("gst_no_verified", models.BooleanField(default=False)),
                ("about_company", models.TextField(null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=150, null=True)),
                ("designation", models.CharField(max_length=150, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("inactive", "inactive"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("unique_code", models.CharField(max_length=50, null=True)),
                ("cin_no", models.CharField(max_length=50, null=True)),
                ("risk_and_compliance_title", models.BooleanField(default=False)),
                ("udhyam_aadharcard", models.CharField(max_length=100, null=True)),
                ("udhyam_aadharcard_verified", models.BooleanField(default=False)),
                (
                    "registered_business_address_building",
                    models.CharField(max_length=150, null=True),
                ),
                (
                    "registered_business_address_area",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "registered_business_address_landmark",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "registered_business_address_state",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "registered_business_address_city",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "trading_address_building",
                    models.CharField(max_length=150, null=True),
                ),
                ("trading_address_area", models.CharField(max_length=100, null=True)),
                (
                    "trading_address_landmark",
                    models.CharField(max_length=100, null=True),
                ),
                ("trading_address_state", models.CharField(max_length=100, null=True)),
                ("trading_address_city", models.CharField(max_length=100, null=True)),
                ("active_subscription", models.BooleanField(default=False)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("days_to_expire", models.IntegerField(default=0)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="CompanyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("person_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "company_email",
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_perc", models.IntegerField(default=0)),
                ("company_material_perc", models.IntegerField(default=0)),
                ("site_location_perc", models.IntegerField(default=0)),
                ("user_role_perc", models.IntegerField(default=0)),
                ("employee_perc", models.IntegerField(default=0)),
                ("pr_release_perc", models.IntegerField(default=0)),
                ("business_setting_perc", models.IntegerField(default=0)),
                ("vendor_perc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "company_profile",
            },
        ),
        migrations.CreateModel(
            name="KeyPersons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=50, null=True)),
                ("designation", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("contact_number", models.CharField(max_length=15, null=True)),
                ("department", models.CharField(max_length=100, null=True)),
                ("deleted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "key_persons",
            },
        ),
    ]
