# Generated by Django 5.2.5 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["deleted", "status"], name="company_del_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["created_at"], name="company_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["updated_at"], name="company_updated_at_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["expiry_date"], name="company_expiry_date_idx"),
        ),
        migrations.AddIndex(
            model_name="keypersons",
            index=models.Index(
                fields=["company", "deleted"], name="keypersons_company_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keypersons",
            index=models.Index(fields=["created_at"], name="keypersons_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["company", "deleted"], name="attachment_company_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["created_at"], name="attachment_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="companyemail",
            index=models.Index(
                fields=["company", "deleted"], name="companyemail_company_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyemail",
            index=models.Index(fields=["created_at"], name="companyemail_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(fields=["company"], name="companyprofile_company_idx"),
        ),
    ]
