# Generated by Django 6.0.3 on 2026-03-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='communication_address_area',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gst_address_area',
        ),
    ]
