# Generated by Django 5.2.5 on 2026-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyphoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyservice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
