# Generated by Django 6.0.3 on 2026-03-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssetting',
            name='end_client',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='partner_company',
        ),
    ]
