# Generated by Django 5.2.5 on 2026-04-16 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0010_remove_userprofile_language_userprofile_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("completion_percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employment_type", models.CharField(max_length=50)),
                (
                    "current_job_title",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                (
                    "highest_education",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("career_goal", models.CharField(max_length=100)),
                ("constraints", models.JSONField(blank=True, default=list)),
                ("work_mode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "work_structure",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preferred_industries", models.JSONField(blank=True, default=list)),
                ("career_values", models.JSONField(blank=True, default=list)),
                (
                    "expected_salary_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transition_timeline",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_profile_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_profile_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_profile_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "professional_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(max_length=50)),
                ("child_name", models.CharField(max_length=150)),
                ("child_education_level", models.CharField(max_length=100)),
                ("stream", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "academic_performance",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("child_interests", models.JSONField(blank=True, default=list)),
                ("support_level", models.CharField(max_length=50)),
                ("child_goal", models.CharField(max_length=100)),
                ("parent_expectations", models.JSONField(blank=True, default=list)),
                ("concerns", models.JSONField(blank=True, default=list)),
                ("constraints", models.JSONField(blank=True, default=list)),
                ("career_awareness", models.CharField(max_length=50)),
                ("decision_style", models.CharField(max_length=50)),
                ("values", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "parent_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorporateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_type", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("company_size", models.CharField(max_length=50)),
                ("hiring_purpose", models.JSONField(blank=True, default=list)),
                ("roles_hiring_for", models.JSONField(blank=True, default=list)),
                ("experience_level", models.CharField(max_length=50)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("training_needs", models.JSONField(blank=True, default=list)),
                ("target_candidates", models.JSONField(blank=True, default=list)),
                ("engagement_model", models.JSONField(blank=True, default=list)),
                ("hiring_timeline", models.CharField(max_length=50)),
                ("budget_range", models.CharField(max_length=50)),
                ("company_values", models.JSONField(blank=True, default=list)),
                ("challenges", models.JSONField(blank=True, default=list)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_profile_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_profile_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "corporate_profile",
                "ordering": ["-created_at"],
            },
        ),
    ]
