# Generated by Django 5.2.5 on 2026-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_profile_professionalprofile_parentprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent / Guardian"),
                    ("working_professional", "Working Professional"),
                    ("institute", "Institute / Course Provider"),
                    ("corporate", "Corporate / Employer"),
                ],
                help_text="User role selected during onboarding",
                max_length=20,
                null=True,
            ),
        ),
    ]
