# Generated by Django 6.0.3 on 2026-04-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0012_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
