# Generated by Django 5.2.5 on 2026-04-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0014_alter_career_goal_to_jsonfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="career_goal",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="career_values",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interest_categories",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="parent_support_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="platform_goals",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="science_track",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_concerns",
        ),
    ]
