# Generated by Django 5.2.5 on 2026-04-17 05:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0015_remove_userprofile_career_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="career_goal",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("study_further", "Study Further"),
                        ("find_job", "Find a Job"),
                        ("internship", "Internship"),
                        ("skill_development", "Skill Development"),
                        ("not_sure", "Not Sure Yet"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="career_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("high_salary_potential", "High Salary Potential"),
                        ("job_security_stability", "Job Security and Stability"),
                        ("creativity_innovation", "Creativity and Innovation"),
                        ("work_life_balance", "Work Life Balance"),
                        ("social_impact", "Making an Impact on Society"),
                        ("growth_and_learning", "Opportunities to Grow and Learn"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interest_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("technology", "Technology / Coding"),
                        ("healthcare", "Healthcare"),
                        ("business_management", "Business Management"),
                        ("agriculture", "Agriculture / Food"),
                        ("creative_design", "Creative / Design"),
                        ("sports_fitness", "Sports / Fitness"),
                        ("government", "Government / Public Service"),
                        ("engineering", "Engineering"),
                        ("finance", "Finance"),
                        ("education", "Education"),
                        ("law", "Law"),
                        ("science_research", "Science & Research"),
                        ("social_welfare", "Social Welfare"),
                        ("hospitality", "Hospitality"),
                        ("vocational", "Vocational / Trades"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Broad interest categories e.g. ['technology', 'healthcare', 'government']",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="parent_support_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_supportive", "Very Supportive"),
                    ("somewhat_supportive", "Somewhat Supportive"),
                    ("neutral", "Neutral"),
                    ("somewhat_restrictive", "Somewhat Restrictive"),
                    ("very_restrictive", "Very Restrictive"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="platform_goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("career_clarity", "Career Clarity"),
                        ("course_recommendations", "Course Recommendations"),
                        (
                            "job_internship_opportunities",
                            "Job / Internship Opportunities",
                        ),
                        ("parent_confidence", "Parent Confidence"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="science_track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pcm", "PCM (Physics, Chemistry, Maths)"),
                    ("pcb", "PCB (Physics, Chemistry, Biology)"),
                    ("pcmb", "PCMB (All four)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_concerns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("job_security", "Job Security"),
                        ("future_demand", "Future Demand"),
                        ("wrong_career_choice", "Wrong Career Choice"),
                        ("high_education_cost", "High Education Cost"),
                        ("limited_guidance", "Limited Guidance"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
