# Generated by Django 5.2.5 on 2026-04-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0016_userprofile_career_goal_userprofile_career_values_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="career_goal",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interest_categories",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="parent_support_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_concerns",
        ),
    ]
