# Generated by Django 5.2.5 on 2026-04-22 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0003_initial"),
        ("country", "0002_initial"),
        ("education_level", "0004_educationlevel_next_steps"),
        ("language_master", "0001_initial"),
        ("state", "0002_initial"),
        ("stream", "0002_initial"),
        ("user_profile", "0017_remove_userprofile_career_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="career_values",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="education_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="platform_goals",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="science_track",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="stream",
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "science_track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pcm", "PCM (Physics, Chemistry, Maths)"),
                            ("pcb", "PCB (Physics, Chemistry, Biology)"),
                            ("pcmb", "PCMB (All four)"),
                        ],
                        help_text="Science track selection for students",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("english", "English"),
                            ("hindi", "Hindi"),
                            ("gujarati", "Gujarati"),
                        ],
                        help_text="Instruction medium of student's school",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="city.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="country.country",
                    ),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="education_level.educationlevel",
                    ),
                ),
                (
                    "language",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Preferred languages selected from Language master",
                        related_name="student_profiles",
                        to="language_master.language",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="state.state",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="stream.stream",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_profile",
            },
        ),
    ]
