# Generated by Django 5.2.5 on 2026-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0018_remove_userprofile_career_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
