# Generated by Django 5.2.5 on 2026-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0019_alter_studentprofile_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="achievements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="additional_insights",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="career_direction",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="extra_activities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="interships",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="projects",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.JSONField(blank=True, default=True, null=True),
        ),
    ]
