# Generated by Django 5.2.5 on 2026-04-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0020_remove_studentprofile_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="interships",
            new_name="internships",
        ),
    ]
