# Generated by Django 5.2.5 on 2026-04-23 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0004_educationlevel_next_steps"),
        ("language_master", "0001_initial"),
        ("stream", "0002_initial"),
        ("user_profile", "0021_rename_interships_studentprofile_internships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["user"], name="student_pro_user_id_c3e7bb_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["education_level"], name="student_pro_educati_ffac7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["stream"], name="student_pro_stream__ae0f69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["science_track"], name="student_pro_science_55783f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["medium"], name="student_pro_medium_48b8ca_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("science_track__in", ["pcm", "pcb", "pcmb"]),
                    ("science_track__isnull", True),
                    _connector="OR",
                ),
                name="valid_science_track",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("medium__in", ["english", "hindi", "gujarati"]),
                    ("medium__isnull", True),
                    _connector="OR",
                ),
                name="valid_medium",
            ),
        ),
    ]
