# Generated by Django 5.2.5 on 2026-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0022_alter_studentprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkdin_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="portfolio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
