# Generated by Django 5.2.5 on 2026-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0023_studentprofile_github_url_studentprofile_linkdin_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
