# Generated by Django 5.2.5 on 2026-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0024_alter_studentprofile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
