# Generated by Django 5.2.5 on 2026-04-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0025_alter_studentprofile_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentprofile",
            name="valid_science_track",
        ),
        migrations.RemoveConstraint(
            model_name="studentprofile",
            name="valid_medium",
        ),
    ]
