# Generated by Django 6.0.3 on 2026-04-24 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_level', '0004_educationlevel_next_steps'),
        ('language_master', '0001_initial'),
        ('user_profile', '0026_remove_studentprofile_valid_science_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='highest_education',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to='education_level.educationlevel'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Preferred languages selected from Language master', related_name='professional_profiles', to='language_master.language'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='linkdin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='professional_profiles', to='skill_category.skillcategory'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='career_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='employment_type',
            field=models.CharField(choices=[('salaried_employee', 'Salaried Employee'), ('self_employed', 'Self-employed / Business Owner'), ('freelancer', 'Freelancer'), ('job_seeker', 'Looking for first job')], help_text='Current employment status', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], help_text='Years of professional experience', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['user'], name='professiona_user_id_3fdd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['education_level'], name='professiona_educati_2a9a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['employment_type'], name='professiona_employm_c08cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['years_of_experience'], name='professiona_years_o_fec609_idx'),
        ),
    ]
