# Generated by Django 6.0.3 on 2026-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_remove_professionalprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='guidance_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='career_goal',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote / Work from home'), ('hybrid', 'Hybrid (office + remote)'), ('office', 'Office-based'), ('field', 'Field work / Travel')], help_text='Work environment preference', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='work_structure',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed 9-5 schedule'), ('flexible', 'Flexible hours'), ('project', 'Project-based'), ('freelance', 'Freelance / Contract')], help_text='Work structure preference', max_length=20, null=True),
        ),
    ]
