# Generated by Django 5.2.5 on 2026-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0029_remove_professionalprofile_guidance_reasons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="career_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("career_change", "Career Change"),
                    ("promotion_growth", "Promotion/Growth"),
                    ("upskill_learn_newskill", "Upskill/Learn new skills"),
                    ("start_own_business", "Start own business"),
                    ("find_a_job", "Find a Job"),
                    ("not_sure_yet", "Not sure yet"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
