# Generated by Django 5.2.5 on 2026-04-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0030_alter_professionalprofile_career_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionalprofile",
            name="career_goal",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="career_values",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="constraints",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="expected_salary_range",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="preferred_industries",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="transition_timeline",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="work_mode",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="work_structure",
        ),
    ]
