# Generated by Django 5.2.5 on 2026-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0031_remove_professionalprofile_career_goal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionalprofile",
            old_name="linkdin_url",
            new_name="linkedin_url",
        ),
        migrations.RenameField(
            model_name="studentprofile",
            old_name="linkdin_url",
            new_name="linkedin_url",
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="additional_insights",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="career_direction",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="key_highlights",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="work_experience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
