# Generated by Django 5.2.5 on 2026-05-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0017_remove_parentprofile_child_interests_and_more"),
        ("user_profile", "0034_alter_parentprofile_academic_performance"),
    ]

    operations = []
