# Generated by Django 5.2.5 on 2026-05-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0035_merge_20260504_1228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="child_interests",
        ),
    ]
