# Generated by Django 6.0.3 on 2026-05-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_alter_businesssetting_created_at_and_more'),
        ('user_profile', '0036_remove_parentprofile_child_interests'),
    ]

    operations = [
    ]
