# Generated by Django 5.2.5 on 2026-05-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0018_alter_businesssetting_created_at_and_more"),
        ("user_profile", "0036_remove_parentprofile_child_interests"),
    ]

    operations = []
