# Generated by Django 5.2.5 on 2026-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0037_merge_20260505_1233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentprofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
