# Generated by Django 6.0.3 on 2026-05-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0037_merge_20260505_1233'),
        ('user_profile', '0038_alter_parentprofile_updated_at_and_more'),
    ]

    operations = [
    ]
