# Generated by Django 6.0.3 on 2026-06-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0039_merge_20260505_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipProfileSkill',
        ),
    ]
