# Generated by Django 6.0.3 on 2026-06-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0039_merge_20260505_1316"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS internship_profile_skill CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="InternshipProfileSkill",
                ),
            ],
        ),
    ]
