# Generated by Django 6.0.3 on 2026-06-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0040_delete_internshipprofileskill"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS internship_profile CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="internshipprofile",
                    name="deleted_by",
                ),
                migrations.RemoveField(
                    model_name="internshipprofile",
                    name="domains",
                ),
                migrations.RemoveField(
                    model_name="internshipprofile",
                    name="profile",
                ),
                migrations.RemoveField(
                    model_name="internshipprofile",
                    name="updated_by",
                ),
                migrations.DeleteModel(
                    name="InternshipApplication",
                ),
                migrations.DeleteModel(
                    name="InternshipProfile",
                ),
            ],
        ),
    ]
