# Generated by Django 6.0.3 on 2026-06-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0042_add_parent_other_relationship_text'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parentprofile',
            name='parent_prof_child_e_f7abed_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentprofile',
            name='parent_prof_stream__ccb9a9_idx',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='academic_performance',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='child_education_level',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='stream',
        ),
        migrations.RunSQL(
            sql="ALTER TABLE parent_profile DROP COLUMN IF EXISTS child_interests;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
