# Generated by Django 6.0.3 on 2026-06-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0005_alter_educationlevel_updated_at"),
        ("stream", "0007_sync_latest_stream_catalog"),
        (
            "user_profile",
            "0043_remove_parentprofile_parent_prof_child_e_f7abed_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "academic_performance",
                    models.CharField(
                        choices=[
                            ("average", "Average"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_screen",
                    models.CharField(
                        choices=[("add_child", "Add Child"), ("complete", "Complete")],
                        default="add_child",
                        max_length=32,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "education_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_profiles",
                        to="education_level.educationlevel",
                    ),
                ),
                (
                    "parent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="user_profile.parentprofile",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_profiles",
                        to="stream.stream",
                    ),
                ),
            ],
            options={
                "db_table": "parent_child_profile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent_profile"], name="parent_chil_parent__b020e6_idx"
                    ),
                    models.Index(
                        fields=["education_level"],
                        name="parent_chil_educati_da5463_idx",
                    ),
                    models.Index(
                        fields=["stream"], name="parent_chil_stream__6f8033_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", False)),
                        fields=(
                            "parent_profile",
                            "first_name",
                            "last_name",
                            "date_of_birth",
                        ),
                        name="unique_active_child_per_parent",
                    )
                ],
            },
        ),
    ]
