# Generated by Django 6.0.3 on 2026-06-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0044_add_childprofile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='current_screen',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='is_completed',
        ),
    ]
