# Generated by Django 6.0.3 on 2026-06-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0048_alter_corporateprofile_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_pro_science_55783f_idx",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="science_track",
        ),
    ]
