# Generated by Django 6.0.3 on 2026-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_master", "0002_alter_language_updated_at"),
        ("user_profile", "0048_alter_corporateprofile_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_pro_science_55783f_idx",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="science_track",
        ),
        migrations.AddField(
            model_name="childprofile",
            name="achievements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="additional_insights",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="career_direction",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="extra_activities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="github_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="internships",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="language",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_profiles",
                to="language_master.language",
            ),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="portfolio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="preferred_job_locations",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="projects",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
