# Generated by Django 6.0.3 on 2026-06-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0049_studentprofile_and_childprofile_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolcollegeprofile",
            name="key_highlights",
        ),
    ]
