# Generated by Django 6.0.3 on 2026-06-30 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0020_remove_retired_content_types"),
        ("education_level", "0005_alter_educationlevel_updated_at"),
        ("language_master", "0002_alter_language_updated_at"),
        ("stream", "0007_sync_latest_stream_catalog"),
        ("user_profile", "0049_studentprofile_and_childprofile_updates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalprofile",
            name="current_industry_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_industry_category_profiles",
                to="domain.domain",
            ),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="employment_type_other_text",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_profiles",
                to="stream.stream",
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("startup_1_50", "Startup (1–50)"),
                    ("small_51_200", "Small (51–200)"),
                    ("medium_201_1000", "Medium (201–1000)"),
                    ("large_1000_plus", "Large (1000+)"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="current_industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_industry_profiles",
                to="domain.domain",
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salaried_employee", "Salaried Employee"),
                    ("self_employed_business_owner", "Self Employed / Business Owner"),
                    ("freelancer", "Freelancer"),
                    ("looking_for_first_job", "Looking for first job"),
                    ("other", "Other"),
                ],
                help_text="Current employment status",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="years_of_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0_1_years", "0–1 years"),
                    ("1_3_years", "1–3 years"),
                    ("3_5_years", "3–5 years"),
                    ("5_plus_years", "5+ years"),
                ],
                help_text="Years of professional experience",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(
                fields=["current_industry_category"],
                name="professiona_current_66d64d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(
                fields=["current_industry"], name="professiona_current_610354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalprofile",
            index=models.Index(
                fields=["stream"], name="professiona_stream__89e9c2_idx"
            ),
        ),
    ]
