# Generated by Django 6.0.3 on 2026-06-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0005_alter_educationlevel_updated_at"),
        ("user_profile", "0050_remove_schoolcollegeprofile_key_highlights"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="board",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="school_college_profiles",
                to="education_level.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="institute_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="total_student",
            field=models.CharField(
                choices=[
                    ("under_500", "Under 500"),
                    ("500_1000", "500-1000"),
                    ("1000_3000", "1000-3000"),
                    ("above_3000", "3000+"),
                ],
                default="under_500",
                max_length=50,
            ),
        ),
    ]
