# Generated by Django 6.0.3 on 2026-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_level", "0005_alter_educationlevel_updated_at"),
        ("user_profile", "0051_schoolcollegeprofile_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolcollegeprofile",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                related_name="school_college_profiles",
                to="education_level.educationlevel",
            ),
        ),
    ]
