# Generated by Django 6.0.3 on 2026-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0052_alter_schoolcollegeprofile_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="partnership_readiness",
            field=models.CharField(
                choices=[
                    ("immediately", "Immediately"),
                    ("within_1month", "Within 1 month"),
                    ("within_3month", "Within 3 month"),
                    ("flexible_timeline", "Flexible timeline"),
                ],
                default="flexible_timeline",
                max_length=50,
            ),
        ),
    ]
