# Generated by Django 6.0.3 on 2026-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0053_schoolcollegeprofile_partnership_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="website",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
