# Generated by Django 6.0.3 on 2026-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0054_schoolcollegeprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="instituteprofile",
            name="website",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
