# Generated by Django 6.0.3 on 2026-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0055_instituteprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateprofile",
            name="institute_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="institute_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
