# Generated by Django 6.0.3 on 2026-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0056_corporateprofile_institute_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateprofile",
            name="website",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
