# Generated by Django 6.0.3 on 2026-07-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0057_corporateprofile_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporateprofile",
            name="institute_name",
        ),
    ]
