# Generated by Django 6.0.3 on 2026-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0058_remove_corporateprofile_institute_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
