# Generated by Django 6.0.3 on 2026-07-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0061_studentprofile_updated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="created_at",
        ),
    ]
