# Generated by Django 6.0.3 on 2026-07-06 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0063_alter_instituteprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalprofile",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="created_at",
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
