# Generated by Django 6.0.3 on 2026-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0064_alter_professionalprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("english", "English"),
                    ("hindi", "Hindi"),
                    ("gujarati", "Gujarati"),
                    ("marathi", "Marathi"),
                    ("tamil", "Tamil"),
                    ("telugu", "Telugu"),
                    ("kannada", "Kannada"),
                    ("bengali", "Bengali"),
                    ("punjabi", "Punjabi"),
                    ("odia", "Odia"),
                    ("malayalam", "Malayalam"),
                    ("urdu", "Urdu"),
                ],
                help_text="Instruction medium of student's school",
                max_length=20,
                null=True,
            ),
        ),
    ]
