# Generated by Django 6.0.3 on 2026-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0066_professionalprofile_referred_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateprofile",
            name="default_token_limit",
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name="corporateprofile",
            name="extra_token_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corporateprofile",
            name="last_token_reset_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporateprofile",
            name="token_limit",
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="default_token_limit",
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="extra_token_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="last_token_reset_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="token_limit",
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="default_token_limit",
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="extra_token_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="last_token_reset_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolcollegeprofile",
            name="token_limit",
            field=models.IntegerField(default=15000),
        ),
    ]
