# Generated by Django 6.0.3 on 2026-07-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0067_add_org_token_limit_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporateprofile",
            name="default_token_limit",
        ),
        migrations.RemoveField(
            model_name="instituteprofile",
            name="default_token_limit",
        ),
        migrations.RemoveField(
            model_name="schoolcollegeprofile",
            name="default_token_limit",
        ),
    ]
