# Generated by Django 6.0.3 on 2026-08-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0070_childprofile_created_by_childprofile_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_code", models.CharField(max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("balance_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization owner whose token pool was charged.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_token_usage_org",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose generation consumed the quota (owner or staff).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_token_usage_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_token_usage",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="organizatio_organiz_a4248f_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="organizatio_user_id_d466be_idx",
                    ),
                ],
            },
        ),
    ]
