# Generated by Django 5.2.1 on 2026-03-25 09:21

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_level', '0003_remove_educationlevel_education_l_is_arch_828752_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='career.careerimportbatch')),
            ],
            options={
                'db_table': 'career_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_code', models.CharField(max_length=64)),
                ('career_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('max_education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='careers_max_level', to='education_level.educationlevel')),
                ('min_education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='careers_min_level', to='education_level.educationlevel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career',
                'indexes': [models.Index(fields=['career_code'], name='career_career__c19305_idx'), models.Index(fields=['is_active'], name='career_is_acti_1634e8_idx'), models.Index(fields=['is_archived'], name='career_is_arch_e45e51_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('career_code'), name='career_career_code_ci_uniq')],
            },
        ),
    ]
