# Generated by Django 6.0.3 on 2026-03-26 11:53

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('education_level', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='career',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='career',
            name='max_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_max_level', to='education_level.educationlevel'),
        ),
        migrations.AddField(
            model_name='career',
            name='min_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_min_level', to='education_level.educationlevel'),
        ),
        migrations.AddField(
            model_name='career',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careerimportbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careerimporterror',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='career.careerimportbatch'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['career_code'], name='career_career__c19305_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['is_active'], name='career_is_acti_1634e8_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['deleted'], name='career_deleted_d7ecae_idx'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('career_code'), name='career_career_code_ci_uniq'),
        ),
    ]
