# Generated by Django 5.2.1 on 2026-03-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('education_level', '0003_remove_educationlevel_education_l_is_arch_828752_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='max_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_max_level', to='education_level.educationlevel'),
        ),
        migrations.AlterField(
            model_name='career',
            name='min_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_min_level', to='education_level.educationlevel'),
        ),
    ]
