# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_initial'),
        ('city_areas', '0002_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=50, null=True)),
                ('document_file', models.CharField(max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_company_document',
            },
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_company_logo', models.CharField(max_length=250, null=True)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gst_address_building', models.CharField(max_length=150, null=True)),
                ('gst_address_landmark', models.CharField(max_length=100, null=True)),
                ('gst_address_pincode', models.IntegerField(null=True)),
                ('communication_address_building', models.CharField(max_length=150, null=True)),
                ('communication_address_landmark', models.CharField(max_length=100, null=True)),
                ('communication_address_pincode', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=25)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('communication_address_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_company_comm_area', to='city_areas.cityarea')),
                ('communication_address_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_company_comm_city', to='city.city')),
                ('communication_address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_company_comm_country', to='country.country')),
            ],
            options={
                'db_table': 'partner_company',
            },
        ),
    ]
