# Generated by Django 5.2.5 on 2026-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_company", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnercompany",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="partnercompanydocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
