"""
Django settings for future4u project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-oxpz+z-9f7_jrz=2q_#3slp7)k^_xz8ua^yu+-g(12itz##71!"
SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    h.strip() for h in config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
]

# ── CORS Configuration ────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config(
        "CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config(
        "CSRF_TRUSTED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
]

# ── Security headers (safe in both dev and prod) ──────────────────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# ── HTTPS enforcement (only active when DEBUG=False) ──────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "django_extensions",
    "corsheaders",
    "rest_framework_simplejwt",
    "activity_log",
    "business_category",
    "career",
    "city",
    "city_areas",
    "common",
    "core",
    "company",
    "country",
    "domain",
    "education_level",
    "employee",
    "end_client",
    "faq",
    "partner_company",
    "pincode",
    "state",
    "subscription",
    "stream",
    "stream_domain_mapping",
    "domain_skill_mapping",
    "domain_career_mapping",
    "assessment",
    "skill",
    "user",
    "user_skill",
    "user_profile",
    "recommendation",
    "language_master",
    "resume_builder",
    "assessment_career",
    "course",
    "internship_job",
    "job_generation",
    "course_generation",
    "internship_generation",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Optional analytics/tracking layer (safe, disabled by default).
if str(config("ANALYTICS_ENABLED", default="0")).lower() in ("1", "true", "yes"):
    MIDDLEWARE.append("utils.analytics_middleware.ApiAnalyticsMiddleware")

ROOT_URLCONF = "future4u.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "future4u.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
AUTH_USER_MODEL = "user.User"

# ── File Upload Settings ─────────────────────────────────────────────────────
MAX_UPLOAD_FILE_SIZE_MB = config("MAX_UPLOAD_FILE_SIZE_MB", default=50, cast=int)

# ── Cache ─────────────────────────────────────────────────────────────────────
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "future4u-cache",
    }
}

# ── REST Framework ────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.Pagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        "user_burst": "30/min",
        "user_sustained": "300/hour",
        "recommendation": "10/min",
        "job_generation": "10/min",
        "course_generation": "10/min",
        "internship_generation": "10/min",
    },


}

# ── Logging ───────────────────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": config("DJANGO_LOG_LEVEL", default="WARNING"),
            "propagate": False,
        },
        "assessment": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "recommendation": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "resume_builder": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "job_generation": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "course_generation": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "internship_generation": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
}


GROQ_API_KEY = config("GROQ_API_KEY", default="").strip()
GROQ_MODEL = config("GROQ_MODEL", default="openai/gpt-oss-120b")
GROQ_TEMPERATURE = config("GROQ_TEMPERATURE", default=0.2, cast=float)
GROQ_MAX_TOKENS = config("GROQ_MAX_TOKENS", default=3000, cast=int)
GROQ_REASONING_EFFORT = config("GROQ_REASONING_EFFORT", default="low").strip()

AI_RECOMMENDATIONS_ENABLED = config(
    "AI_RECOMMENDATIONS_ENABLED",
    default=True,
    cast=bool,
)
AI_TRACING_ENABLED = config("AI_TRACING_ENABLED", default=False, cast=bool)

JOB_GENERATION_ENABLED = config(
    "JOB_GENERATION_ENABLED",
    default=True,
    cast=bool,
)
JOB_GENERATION_LLM_PROVIDER = config(
    "JOB_GENERATION_LLM_PROVIDER",
    default="groq",
).strip().lower()
JOB_GENERATION_MAX_TOKENS = config(
    "JOB_GENERATION_MAX_TOKENS",
    default=3000,
    cast=int,
)
JOB_GENERATION_TEMPERATURE = config(
    "JOB_GENERATION_TEMPERATURE",
    default=0.2,
    cast=float,
)

COURSE_GENERATION_ENABLED = config(
    "COURSE_GENERATION_ENABLED",
    default=True,
    cast=bool,
)
COURSE_GENERATION_LLM_PROVIDER = config(
    "COURSE_GENERATION_LLM_PROVIDER",
    default="groq",
).strip().lower()
COURSE_GENERATION_MAX_TOKENS = config(
    "COURSE_GENERATION_MAX_TOKENS",
    default=3000,
    cast=int,
)
COURSE_GENERATION_TEMPERATURE = config(
    "COURSE_GENERATION_TEMPERATURE",
    default=0.2,
    cast=float,
)

INTERNSHIP_GENERATION_ENABLED = config(
    "INTERNSHIP_GENERATION_ENABLED",
    default=True,
    cast=bool,
)
INTERNSHIP_GENERATION_LLM_PROVIDER = config(
    "INTERNSHIP_GENERATION_LLM_PROVIDER",
    default="groq",
).strip().lower()
INTERNSHIP_GENERATION_MAX_TOKENS = config(
    "INTERNSHIP_GENERATION_MAX_TOKENS",
    default=3000,
    cast=int,
)
INTERNSHIP_GENERATION_TEMPERATURE = config(
    "INTERNSHIP_GENERATION_TEMPERATURE",
    default=0.2,
    cast=float,
)

OPENAI_API_KEY = config("OPENAI_API_KEY", default="").strip()
OPENAI_MODEL = config("OPENAI_MODEL", default="gpt-4o-mini").strip()
GEMINI_API_KEY = config("GEMINI_API_KEY", default="").strip()
GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-1.5-flash").strip()

# LangSmith only — private settings; never used in recommendation pipeline or API output.
_LANGSMITH_TRACING_ENABLED = AI_TRACING_ENABLED or config(
    "LANGCHAIN_TRACING_V2",
    default=config("LANGSMITH_TRACING_V2", default=False),
    cast=bool,
)
_LANGSMITH_API_KEY = config(
    "LANGSMITH_API_KEY",
    default=config("LANGCHAIN_API_KEY", default=""),
).strip()
_LANGSMITH_PROJECT = config(
    "LANGSMITH_PROJECT",
    default=config("LANGCHAIN_PROJECT", default="future4u"),
)

from future4u.langsmith_tracing import apply_langsmith_tracing_env

apply_langsmith_tracing_env(
    enabled=_LANGSMITH_TRACING_ENABLED,
    api_key=_LANGSMITH_API_KEY,
    project=_LANGSMITH_PROJECT,
)

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
FRONTEND_URL = "https://app.future4u.ai"

CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
