# Generated by Django 5.2.5 on 2026-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=201, null=True
            ),
        ),
    ]
