# Generated by Django 6.0.3 on 2026-03-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='end_client',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='partner_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='partner_company',
        ),
    ]
