# Generated by Django 5.2.5 on 2026-04-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_city_user_country_user_states"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="aadhar_card",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="current_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="user",
            name="message",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pancard",
        ),
        migrations.RemoveField(
            model_name="user",
            name="permanent_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="whatsapp_otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="whatsapp_verified",
        ),
    ]
