# Generated by Django 5.2.5 on 2026-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_role_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
