# Generated by Django 5.2.5 on 2026-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="student", max_length=15),
        ),
    ]
