# Generated by Django 5.2.5 on 2026-04-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_initial"),
        ("user", "0010_add_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="country.country",
            ),
        ),
    ]
