# Generated by Django 5.2.5 on 2026-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_user_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent / Guardian"),
                    ("working_professional", "Working Professional"),
                    ("school_college", "School / College"),
                    ("institute", "Institute / Course Provider"),
                    ("corporate", "Corporate / Employer"),
                    ("super_user", "Super User"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
