# Generated by Django 5.2.5 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_user_role_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent / Guardian"),
                    ("working_professional", "Working Professional"),
                    ("school_college", "School / College"),
                    ("institute", "Institute / Course Provider"),
                    ("corporate", "Corporate / Employer"),
                    ("super_admin", "Super Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
