# Generated by Django 6.0.3 on 2026-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_alter_customgroup_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
