# Generated by Django 6.0.3 on 2026-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_add_otp_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
