# Generated by Django 6.0.3 on 2026-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
