# Generated by Django 6.0.3 on 2026-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
