# Generated by Django 6.0.3 on 2026-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
