# Generated by Django 6.0.3 on 2026-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_user_audit_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent / Guardian"),
                    ("working_professional", "Working Professional"),
                    ("school_college", "School / College"),
                    ("institute", "Institute / Course Provider"),
                    ("corporate", "Corporate / Employer"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
