# Generated by Django 6.0.3 on 2026-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_org_staff",
            field=models.BooleanField(
                default=False,
                help_text="True for staff users created by an organization admin. Staff never receive an automatic monthly token allowance.",
            ),
        ),
    ]
