# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('state:create', 'Add State'), ('state:update', 'Modify State'), ('state:archive', 'Archive State'), ('state:restore', 'Restore State'), ('city:create', 'Add City'), ('city:update', 'Modify City'), ('city:archive', 'Archive City'), ('city:restore', 'Restore City'), ('city_area:create', 'Add City Area'), ('city_area:update', 'Modify City Area'), ('city_area:archive', 'Archive City Area'), ('city_area:restore', 'Restore City Area'), ('company:create', 'Add Company'), ('company:update', 'Modify Company'), ('company:archive', 'Archive Company'), ('company:restore', 'Restore Company'), ('company:logo delete', 'Company Logo Detele'), ('company_photo:create', 'Add Company Photo'), ('company_photo:update', 'Modify Company Photo'), ('company_photo:delete', 'Delete Company Photo'), ('company:basic info update', 'Company Basic Info Update'), ('company:password change', 'Company Password Change'), ('company:status update', 'Company Status Change'), ('partner_company:create', 'Add Partner Company'), ('partner_company:update', 'Modify Partner Company'), ('partner_company:archive', 'Archive Partner Company'), ('partner_company:restore', 'Restore Partner Company'), ('partner_company_document:create', 'Add Partner Company Document'), ('partner_company_document:update', 'Modify Partner Company Document'), ('partner_company_document:archive', 'Archive Partner Company Document'), ('partner_company_document:restore', 'Restore Partner Company Document'), ('partner_company:basic info update', 'Partner Company Basic Info Update'), ('partner_company:password change', 'Partner Company Password Change'), ('partner_company:status update', 'Partner Company Status Update'), ('endclient:create', 'Add EndClient'), ('endclient:update', 'Modify EndClient'), ('endclient:archive', 'Archive EndClient'), ('endclient:restore', 'Restore EndClient'), ('endclient:photo delete', 'EndClient Photo Detele'), ('endclient:basic info update', 'EndClient Basic Info Update'), ('endclient:password change', 'EndClient Password Change'), ('endclient:status update', 'EndClient Status Change'), ('employee:create', 'Add Employee'), ('employee:update', 'Modify Employee'), ('employee:archive', 'Archive Employee'), ('employee:restore', 'Restore Employee'), ('country:create', 'Add Country'), ('country:update', 'Modify Country'), ('country:archive', 'Archive Country'), ('country:restore', 'Restore Country'), ('business_category:create', 'Add Business Category'), ('business_category:update', 'Modify Business Category'), ('business_category:archive', 'Archive Business Category'), ('business_category:restore', 'Restore Business Category'), ('notification_template:create', 'Add Notification Template'), ('notification_template:update', 'Modify Notification Template'), ('notification_template:archive', 'Archive Notification Template'), ('notification_template:restore', 'Restore Notification Template'), ('site_location:create', 'Add Site location'), ('site_location:update', 'Modify Site location'), ('site_location:archive', 'Archive Site location'), ('site_location:restore', 'Restore Site location'), ('quotation:create', 'Add Quotation'), ('quotation:update', 'Modify Quotation'), ('quotation:archive', 'Archive Quotation'), ('quotation:restore', 'Restore Quotation'), ('quotation_detail:create', 'Add Quotation Detail'), ('quotation_detail:update', 'Modify Quotation Detail'), ('quotation_detail:archive', 'Archive Quotation Detail'), ('quotation_detail:restore', 'Restore Quotation Detail'), ('quotation_query:create', 'Add Quotation Query'), ('quotation_query:update', 'Modify Quotation Query'), ('quotation_query:archive', 'Archive Quotation Query'), ('quotation_query:restore', 'Restore Quotation Query'), ('request_demo:create', 'Add Request Demo'), ('request_demo:update', 'Modify Request Demo'), ('request_demo:archive', 'Archive Request Demo'), ('request_demo:restore', 'Restore Request Demo'), ('subscription:create', 'Add Subscription'), ('subscription:update', 'Modify Subscription'), ('subscription:archive', 'Archive Subscription'), ('subscription:restore', 'Restore Subscription'), ('purchased_subscription:create', 'Add Purchased  Subscription'), ('purchased_subscription:update', 'Modify Purchased Subscription'), ('purchased_subscription:archive', 'Archive Purchased Subscription'), ('purchased_subscription:restore', 'Restore Purchased Subscription'), ('subscription_feature:create', 'Add Subscription Feature'), ('subscription_feature:update', 'Modify Subscription Feature'), ('subscription_feature:archive', 'Archive Subscription Feature'), ('subscription_feature:restore', 'Restore Subscription Feature'), ('subscription_invoice:create', 'Add Subscription Invoice'), ('subscription_invoice:update', 'Modify Subscription Invoice'), ('subscription_invoice:archive', 'Archive Subscription Invoice'), ('subscription_invoice:restore', 'Restore Subscription Invoice'), ('business_setting:update', 'Modify Business Setting'), ('faq:update', 'Modify FAQ'), ('faq:archive', 'Archive FAQ'), ('faq:restore', 'Restore FAQ'), ('meter_config:create', 'Add Meter Config'), ('meter_config:update', 'Modify Meter Config'), ('meter_config:archive', 'Archive Meter Config'), ('meter_config:restore', 'Restore Meter Config'), ('device_configuration:create', 'Add Device Configuration'), ('device_configuration:update', 'Modify Device Configuration'), ('device_configuration:assign', 'Assign Device Configuration'), ('device_configuration:edit_site', 'Edit Device Configuration Site'), ('device_configuration:update_status', 'Update Device Configuration Status'), ('device_configuration:create_schedule', 'Create Device Configuration Schedule'), ('device_configuration:update_schedule', 'Update Device Configuration Schedule'), ('device_configuration:power_control', 'Device Configuration Power Control'), ('device_configuration:archive', 'Archive Device Configuration'), ('device_configuration:restore', 'Restore Device Configuration'), ('device_transfer:create', 'Add Device Transfer'), ('device_transfer:update', 'Update Device Transfer'), ('device_transfer:edit_request', 'Edit Device Transfer Request'), ('device_transfer:update_status', 'Update Device Transfer Status'), ('device_transfer:archive', 'Archive Device Transfer'), ('device_transfer:restore', 'Restore Device Transfer'), ('device_transfer:site_photo_delete', 'Device Transfer Site Photo Delete')], max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('template_name', models.CharField(max_length=255)),
                ('response_code', models.IntegerField()),
                ('response_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'whatsapp_message_log',
            },
        ),
    ]
