# Generated by Django 6.0.3 on 2026-03-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_log', '0001_initial'),
        ('business_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='business_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_category.businesscategory'),
        ),
    ]
