# Generated by Django 6.0.3 on 2026-03-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_log', '0002_initial'),
        ('city', '0002_initial'),
        ('city_areas', '0002_initial'),
        ('company', '0003_initial'),
        ('country', '0001_initial'),
        ('employee', '0001_initial'),
        ('end_client', '0001_initial'),
        ('faq', '0001_initial'),
        ('partner_company', '0002_initial'),
        ('state', '0001_initial'),
        ('subscription', '0001_initial'),
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='business_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.businesssetting'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='city_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_areas.cityarea'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='company_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyphoto'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='end_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='end_client.endclient'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.faq'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='partner_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_company.partnercompany'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='partner_company_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_company.partnercompanydocument'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.state'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subscription_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionfeature'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subscription_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptioninvoice'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_whatsapp_logs', to='company.company'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='request_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_user_whatsapp_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
