# Generated by Django 5.2.5 on 2026-03-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity_log", "0003_initial"),
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="currency.currency",
            ),
        ),
    ]
