# Generated by Django 6.0.3 on 2026-03-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='city_area',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='end_client',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='partner_company',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='partner_company_document',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessageLog',
        ),
    ]
