# Generated by Django 6.0.3 on 2026-07-08 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0004_rebuild_activity_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activity_lo_user_id_c97c68_idx",
            old_name="actlog_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activity_lo_event_d21789_idx",
            old_name="actlog_event_created_idx",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="event",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name="activitylog",
            table="activity_log",
        ),
    ]
