# Generated by Django 5.2.5 on 2026-03-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity_log", "0005_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="subcription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subcription",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="subcription_feature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionfeature",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="subscription_invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptioninvoice",
            ),
        ),
    ]
