# Generated by Django 6.0.3 on 2026-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity_log",
            "0005_rename_actlog_user_created_idx_activity_lo_user_id_c97c68_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="entity_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
