# Generated by Django 5.2.1 on 2026-03-24 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('stream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamDomainMappingImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_domain_mapping_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream_domain_mapping_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamDomainMappingImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='stream_domain_mapping.streamdomainmappingimportbatch')),
            ],
            options={
                'db_table': 'stream_domain_mapping_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='StreamDomainMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_score', models.PositiveSmallIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_domain_mappings', to='domain.domain')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_domain_mappings', to='stream.stream')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream_domain_mapping',
                'ordering': ['-weight_score', 'id'],
                'indexes': [models.Index(fields=['stream'], name='stream_doma_stream__d968cb_idx'), models.Index(fields=['domain'], name='stream_doma_domain__e40876_idx'), models.Index(fields=['weight_score'], name='stream_doma_weight__d6494e_idx'), models.Index(fields=['is_active'], name='stream_doma_is_acti_2b0fe7_idx'), models.Index(fields=['deleted'], name='stream_doma_deleted_602f10_idx')],
                'constraints': [models.UniqueConstraint(fields=('stream', 'domain'), name='stream_domain_mapping_stream_domain_uniq'), models.CheckConstraint(condition=models.Q(('weight_score__gte', 0), ('weight_score__lte', 100)), name='stream_domain_mapping_weight_score_0_100_ck')],
            },
        ),
    ]
