# Generated by Django 6.0.3 on 2026-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['category_name']},
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='category_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
