# Generated by Django 5.2.5 on 2026-04-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_category", "0003_alter_skillcategory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillcategory",
            name="category_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
