# Generated by Django 6.0.3 on 2026-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_category', '0004_alter_skillcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
