# Generated by Django 5.2.5 on 2026-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_category", "0005_alter_skillcategory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillcategory",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
