# Generated by Django 5.2.5 on 2026-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_category", "0007_assessmentgoal_assessmentinterestvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentgoal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="assessmentinterestvalue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skillcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
