# Generated by Django 6.0.3 on 2026-06-30 08:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_type", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_read", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_c291d5_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_9edb86_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
