# Generated by Django 5.2.1 on 2026-03-25 08:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('row_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='skill.skillimportbatch')),
            ],
            options={
                'db_table': 'skill_import_error',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_code', models.CharField(max_length=64)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft'), ('analytical', 'Analytical'), ('creative', 'Creative')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill',
                'indexes': [models.Index(fields=['skill_code'], name='skill_skill_c_c0a293_idx'), models.Index(fields=['skill_type'], name='skill_skill_t_1e67f7_idx'), models.Index(fields=['is_active'], name='skill_is_acti_b57a95_idx'), models.Index(fields=['is_archived'], name='skill_is_arch_c11d01_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('skill_code'), name='skill_skill_code_ci_uniq')],
            },
        ),
    ]
